// Owner-confirmed on 18 September 2026. Rates and dates remain on request.
export const LONG_STAY_COPY = {
  ru: {
    wifi: 'Wi‑Fi', heating: 'Газовое отопление', layout: "Апартаменты с одной спальней и террасой",
    hero: "У моря — с домашним комфортом: Wi‑Fi, газовое отопление и собственная терраса.",
    title: 'Останьтесь в Скалее подольше', eyebrow: 'Зима и несезон · длительное проживание',
    intro: "Останьтесь у моря на несколько недель или месяц. Готовьте дома, отдыхайте на собственной террасе и гуляйте по Скалее. Wi‑Fi и газовое отопление помогут сохранить привычный ритм жизни.",
    location: 'Interspar — около 230 м, вокзал — 500 м, ближайший пляж — 600 м. За продуктами и на прогулку можно ходить пешком.',
    terms: "Напишите даты и число гостей — уточним свободные даты, стоимость проживания и оплату коммунальных услуг до бронирования.",
    cta: "Узнать цену на мои даты",
    message: 'Здравствуйте! Интересует длительное проживание в ScaleaStay. Даты: __. Срок проживания: __. Количество гостей: __. Подскажите стоимость и условия коммунальных платежей.',
    seo: 'Апартаменты в Скалее: Wi‑Fi, газовое отопление, кухня и терраса. Одна спальня, пляж — 600 м. Длительное проживание в несезон — по запросу.',
    availabilityCta: "Узнать цену и свободные даты",
    shortCta: "Узнать цену",
    inquiry: "Здравствуйте! Интересуют апартаменты ScaleaStay. Даты: __. Количество гостей: __. Подскажите, свободны ли эти даты и сколько будет стоить проживание?",
    apartmentSummary: "Апартаменты с одной спальней и собственной террасой. Готовьте на оборудованной кухне, отдыхайте после пляжа и выбирайте удобный для вас срок поездки.",
    speedAnswer: "Wi‑Fi подключён. Если вам нужна определённая скорость для работы или видеозвонков, уточните её у владельца перед бронированием.",
    faq: [
      { q: 'Есть ли в квартире Wi‑Fi?', a: "Да, в апартаментах есть Wi‑Fi." },
      { q: 'Есть ли отопление для проживания в несезон?', a: 'Да, в квартире есть газовое отопление. Условия оплаты коммунальных услуг согласуются до бронирования.' },
      { q: 'Можно ли снять квартиру на несколько недель или месяц?', a: "Да, длительное проживание в несезон возможно по согласованию. Напишите в WhatsApp даты и число гостей — уточним стоимость и свободные даты." },
    ],
  },
  en: {
    wifi: 'Wi‑Fi', heating: 'Gas heating', layout: "One-bedroom apartment with a terrace",
    hero: "Feel at home by the sea, with Wi‑Fi, gas heating and your own terrace.",
    title: 'Stay a little longer in Scalea', eyebrow: 'Winter and off-season · longer stays',
    intro: "Make Scalea your home for a few weeks or a month. Cook in the apartment, unwind on your own terrace and explore the town on foot. Wi‑Fi and gas heating make it easier to keep your everyday routine.",
    location: 'Interspar is about 230 m away, the station 500 m and the nearest beach 600 m. Walk to the shops or down to the sea.',
    terms: "Send your dates and number of guests. We’ll confirm availability, the price and utility charges before you book.",
    cta: "Get a quote for my dates",
    message: 'Hello! I am interested in a longer stay at ScaleaStay. Dates: __. Length of stay: __. Number of guests: __. Please share the price and utility terms.',
    seo: 'Scalea apartment with Wi‑Fi, gas heating, kitchen and terrace. One bedroom, beach 600 m away. Longer off-season stays on request.',
    availabilityCta: "Check dates and price",
    shortCta: "Ask for a price",
    inquiry: "Hello! I am interested in the ScaleaStay apartment. Dates: __. Number of guests: __. Is it available and what would the total stay cost?",
    apartmentSummary: "A one-bedroom apartment with your own terrace. Prepare meals in the equipped kitchen, unwind after the beach and stay for a short break or a longer visit.",
    speedAnswer: "Wi‑Fi is connected. If you need a particular speed for work or video calls, please check with the owner before booking.",
    faq: [
      { q: 'Does the apartment have Wi‑Fi?', a: "Yes, Wi‑Fi is available in the apartment." },
      { q: 'Is there heating for off-season stays?', a: 'Yes, the apartment has gas heating. Utility payment terms are agreed before booking.' },
      { q: 'Can I rent the apartment for a few weeks or a month?', a: "Yes, longer off-season stays can be arranged. Send your dates and number of guests on WhatsApp to check the price and availability." },
    ],
  },
  it: {
    wifi: 'Wi‑Fi', heating: 'Riscaldamento a gas', layout: "Appartamento con una camera da letto e terrazza",
    hero: "Al mare, con il comfort di casa: Wi‑Fi, riscaldamento a gas e una terrazza tutta per te.",
    title: 'Fermati più a lungo a Scalea', eyebrow: 'Inverno e fuori stagione · soggiorni prolungati',
    intro: "Vivi Scalea per qualche settimana o un mese. Cucina in appartamento, rilassati sulla tua terrazza e scopri la città a piedi. Wi‑Fi e riscaldamento a gas ti aiutano a mantenere le tue abitudini anche fuori stagione.",
    location: 'Interspar a circa 230 m, la stazione a 500 m e la spiaggia più vicina a 600 m. Puoi fare la spesa e passeggiare al mare a piedi.',
    terms: "Scrivici le date e il numero di ospiti: ti confermeremo disponibilità, prezzo e costi delle utenze prima della prenotazione.",
    cta: "Chiedi un preventivo per le tue date",
    message: 'Buongiorno! Mi interessa un soggiorno prolungato a ScaleaStay. Date: __. Durata: __. Numero di ospiti: __. Vorrei conoscere il prezzo e le condizioni delle utenze.',
    seo: 'Appartamento a Scalea con Wi‑Fi, riscaldamento a gas, cucina e terrazza. Una camera da letto, spiaggia a 600 m. Soggiorni lunghi fuori stagione su richiesta.',
    availabilityCta: "Chiedi disponibilità e prezzo",
    shortCta: "Chiedi un preventivo",
    inquiry: "Buongiorno! Mi interessa l’appartamento ScaleaStay. Date: __. Numero di ospiti: __. È disponibile e qual è il costo del soggiorno?",
    apartmentSummary: "Un appartamento con una camera da letto e una terrazza tutta per te. Prepara i pasti nella cucina attrezzata, rilassati dopo la spiaggia e scegli tra una breve vacanza e un soggiorno più lungo.",
    speedAnswer: "Il Wi‑Fi è attivo. Se ti serve una velocità specifica per lavorare o fare videochiamate, chiedi al proprietario prima di prenotare.",
    faq: [
      { q: 'È disponibile il Wi‑Fi in appartamento?', a: "Sì, il Wi‑Fi è disponibile in appartamento." },
      { q: 'C’è il riscaldamento per i soggiorni fuori stagione?', a: 'Sì, l’appartamento dispone di riscaldamento a gas. Le condizioni di pagamento delle utenze vengono concordate prima della prenotazione.' },
      { q: 'Posso affittare l’appartamento per qualche settimana o un mese?', a: "Sì, i soggiorni prolungati fuori stagione sono possibili previo accordo. Scrivi le date e il numero di ospiti su WhatsApp per conoscere prezzo e disponibilità." },
    ],
  },
  de: {
    wifi: 'WLAN', heating: 'Gasheizung', layout: "Ferienwohnung mit einem Schlafzimmer und Terrasse",
    hero: "Am Meer wie zu Hause: mit WLAN, Gasheizung und eigener Terrasse.",
    title: 'Bleiben Sie länger in Scalea', eyebrow: 'Winter und Nebensaison · längere Aufenthalte',
    intro: "Verbringen Sie einige Wochen oder einen Monat in Scalea. Kochen Sie in Ihrer Ferienwohnung, entspannen Sie auf der eigenen Terrasse und erkunden Sie den Ort zu Fuß. WLAN und Gasheizung erleichtern den Alltag auch in der Nebensaison.",
    location: 'Interspar ist etwa 230 m entfernt, der Bahnhof 500 m und der nächste Strand 600 m. Einkäufe und Spaziergänge am Meer sind zu Fuß möglich.',
    terms: "Senden Sie uns Ihre Reisedaten und die Gästezahl. Verfügbarkeit, Preis und Nebenkosten klären wir vor der Buchung.",
    cta: "Preis für meine Reisedaten anfragen",
    message: 'Hallo! Ich interessiere mich für einen längeren Aufenthalt bei ScaleaStay. Reisedaten: __. Aufenthaltsdauer: __. Gästezahl: __. Bitte teilen Sie mir den Preis und die Nebenkostenbedingungen mit.',
    seo: 'Ferienwohnung in Scalea mit WLAN, Gasheizung, Küche und Terrasse. Ein Schlafzimmer, Strand 600 m entfernt. Längere Aufenthalte auf Anfrage.',
    availabilityCta: "Verfügbarkeit und Preis anfragen",
    shortCta: "Preis anfragen",
    inquiry: "Hallo! Ich interessiere mich für die Ferienwohnung ScaleaStay. Reisedaten: __. Gästezahl: __. Ist die Wohnung verfügbar und was kostet der Aufenthalt?",
    apartmentSummary: "Eine Ferienwohnung mit einem Schlafzimmer und eigener Terrasse. Kochen Sie in der ausgestatteten Küche, entspannen Sie nach dem Strandbesuch und bleiben Sie für einen Kurzurlaub oder länger.",
    speedAnswer: "WLAN ist eingerichtet. Wenn Sie eine bestimmte Geschwindigkeit für Arbeit oder Videoanrufe benötigen, fragen Sie bitte vor der Buchung beim Eigentümer nach.",
    faq: [
      { q: 'Gibt es WLAN in der Wohnung?', a: "Ja, in der Ferienwohnung gibt es WLAN." },
      { q: 'Gibt es eine Heizung für die Nebensaison?', a: 'Ja, die Wohnung hat eine Gasheizung. Die Zahlungsbedingungen für Nebenkosten werden vor der Buchung vereinbart.' },
      { q: 'Kann ich die Wohnung für einige Wochen oder einen Monat mieten?', a: "Ja, längere Aufenthalte in der Nebensaison sind nach Absprache möglich. Senden Sie Reisedaten und Gästezahl per WhatsApp, um Preis und Verfügbarkeit zu erfahren." },
    ],
  },
  cs: {
    wifi: 'Wi‑Fi', heating: 'Plynové topení', layout: "Apartmán s jednou ložnicí a terasou",
    hero: "U moře jako doma: Wi‑Fi, plynové topení a vlastní terasa.",
    title: 'Zůstaňte ve Scalee déle', eyebrow: 'Zima a mimo sezónu · delší pobyty',
    intro: "Zůstaňte ve Scalee na několik týdnů nebo měsíc. Vařte si v apartmánu, odpočívejte na vlastní terase a objevujte město pěšky. Wi‑Fi a plynové topení vám pomohou zachovat běžný rytmus i mimo sezónu.",
    location: 'Interspar je přibližně 230 m daleko, nádraží 500 m a nejbližší pláž 600 m. Na nákupy i na procházku k moři dojdete pěšky.',
    terms: "Napište nám termín a počet hostů. Před rezervací upřesníme dostupnost, cenu pobytu i platby za energie a služby.",
    cta: "Zjistit cenu pro můj termín",
    message: 'Dobrý den! Mám zájem o delší pobyt ve ScaleaStay. Termín: __. Délka pobytu: __. Počet hostů: __. Prosím o cenu a podmínky úhrady energií a služeb.',
    seo: 'Apartmán ve Scalee s Wi‑Fi, plynovým topením, kuchyní a terasou. Jedna ložnice, pláž 600 m. Delší pobyty mimo sezónu na vyžádání.',
    availabilityCta: "Ověřit termín a cenu",
    shortCta: "Zjistit cenu",
    inquiry: "Dobrý den! Mám zájem o apartmán ScaleaStay. Termín: __. Počet hostů: __. Je apartmán volný a kolik by pobyt stál?",
    apartmentSummary: "Apartmán s jednou ložnicí a vlastní terasou. Připravte si jídlo ve vybavené kuchyni, odpočiňte si po návratu z pláže a přijeďte na krátkou dovolenou i delší pobyt.",
    speedAnswer: "Wi‑Fi je připojena. Pokud potřebujete konkrétní rychlost pro práci nebo videohovory, ověřte si ji u majitele před rezervací.",
    faq: [
      { q: 'Je v apartmánu Wi‑Fi?', a: "Ano, v apartmánu je Wi‑Fi." },
      { q: 'Je k dispozici topení pro pobyt mimo sezónu?', a: 'Ano, apartmán má plynové topení. Podmínky úhrady energií a služeb dohodneme před rezervací.' },
      { q: 'Mohu si apartmán pronajmout na několik týdnů nebo měsíc?', a: "Ano, delší pobyt mimo sezónu je možný po domluvě. Napište termín a počet hostů přes WhatsApp a ověříme cenu i dostupnost." },
    ],
  },
  pl: {
    wifi: 'Wi‑Fi', heating: 'Ogrzewanie gazowe', layout: "Apartament z jedną sypialnią i tarasem",
    hero: "Nad morzem jak w domu: Wi‑Fi, ogrzewanie gazowe i własny taras.",
    title: 'Zostań w Scalei na dłużej', eyebrow: 'Zima i poza sezonem · dłuższe pobyty',
    intro: "Zostań w Scalei na kilka tygodni lub miesiąc. Gotuj w apartamencie, odpoczywaj na własnym tarasie i odkrywaj miasto pieszo. Wi‑Fi i ogrzewanie gazowe ułatwiają codzienne życie również poza sezonem.",
    location: 'Interspar jest około 230 m dalej, dworzec 500 m, a najbliższa plaża 600 m. Na zakupy i na spacer nad morze można dojść pieszo.',
    terms: "Napisz termin i liczbę gości. Przed rezerwacją potwierdzimy dostępność, cenę pobytu i zasady opłat za media.",
    cta: "Zapytaj o cenę na wybrany termin",
    message: 'Dzień dobry! Interesuje mnie dłuższy pobyt w ScaleaStay. Termin: __. Długość pobytu: __. Liczba gości: __. Proszę o cenę i zasady opłat za media.',
    seo: 'Apartament w Scalei z Wi‑Fi, ogrzewaniem gazowym, kuchnią i tarasem. Jedna sypialnia, plaża 600 m. Dłuższe pobyty poza sezonem na zapytanie.',
    availabilityCta: "Zapytaj o termin i cenę",
    shortCta: "Zapytaj o cenę",
    inquiry: "Dzień dobry! Interesuje mnie apartament ScaleaStay. Termin: __. Liczba gości: __. Czy apartament jest dostępny i jaki jest koszt pobytu?",
    apartmentSummary: "Apartament z jedną sypialnią i własnym tarasem. Przygotuj posiłek w wyposażonej kuchni, odpocznij po powrocie z plaży i przyjedź na krótki wyjazd lub dłuższy pobyt.",
    speedAnswer: "Wi‑Fi jest podłączone. Jeśli potrzebujesz określonej prędkości do pracy lub rozmów wideo, sprawdź ją u właściciela przed rezerwacją.",
    faq: [
      { q: 'Czy w apartamencie jest Wi‑Fi?', a: "Tak, w apartamencie jest Wi‑Fi." },
      { q: 'Czy jest ogrzewanie na pobyt poza sezonem?', a: 'Tak, apartament ma ogrzewanie gazowe. Zasady rozliczania mediów ustalamy przed rezerwacją.' },
      { q: 'Czy mogę wynająć apartament na kilka tygodni lub miesiąc?', a: "Tak, dłuższy pobyt poza sezonem jest możliwy po uzgodnieniu. Wyślij termin i liczbę gości przez WhatsApp, aby poznać cenę i dostępność." },
    ],
  },
};

export const getLongStayCopy = (language: string) =>
  LONG_STAY_COPY[language as keyof typeof LONG_STAY_COPY] || LONG_STAY_COPY.en;

export const CONFIRMED_AMENITIES = [
  { '@type': 'LocationFeatureSpecification', name: 'Wi-Fi', value: true },
  { '@type': 'LocationFeatureSpecification', name: 'Gas heating', value: true },
];
