import { getNearbyCopy, NEARBY_PLACES, nearbyMap } from './nearby';
import { getPompeiiCopy, POMPEII_MAP, POMPEII_VISIT, POMPEII_TRAVEL, POMPEII_PHOTO_IDS } from './pompeii';
import { NEARBY_PHOTOS } from './nearbyPhotos';

const esc = (text: string) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');

// Shared static content keeps the homepage, no-JS HTML and winter landing consistent.
export function renderNearby(language: string): string {
  const copy = getNearbyCopy(language), pompeii = getPompeiiCopy(language);
  return `<style>
.nearby-section{padding:56px 24px;background:#f8fafc;color:#0f172a;scroll-margin-top:190px;font:16px/1.65 'Roboto',system-ui,sans-serif;overflow-wrap:anywhere}
.nearby-section *{box-sizing:border-box}.nearby-wrap{max-width:1160px;margin:auto}.nearby-section .nearby-eyebrow{color:#4338ca;font-size:12px;letter-spacing:.14em;text-transform:uppercase;font-weight:700;margin:0 0 12px}.nearby-section h2{font-family:'Playfair Display',Georgia,serif;font-size:clamp(28px,3vw,42px);line-height:1.2;margin:0 0 18px;font-weight:700;letter-spacing:-.02em}.nearby-intro{max-width:780px;color:#475569;margin:0 0 28px}.nearby-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.nearby-card{display:flex;flex-direction:column;background:white;border:1px solid #e2e8f0;border-radius:24px;overflow:hidden}.nearby-section .nearby-photo{margin:0;background:#e2e8f0}.nearby-photo img{display:block;width:100%;height:auto;aspect-ratio:16/9;object-fit:cover}.nearby-section .nearby-photo figcaption{padding:8px 24px;background:#f1f5f9;color:#475569;font-size:12px;line-height:1.5}.nearby-card-body{display:flex;flex-direction:column;flex:1;padding:24px}.nearby-section h3{font-family:'Playfair Display',Georgia,serif;font-size:25px;line-height:1.25;font-weight:700;margin:0 0 14px;letter-spacing:-.02em}.nearby-section .nearby-text{margin:0 0 18px;color:#475569}.nearby-details{margin:0 0 18px}.nearby-details summary{cursor:pointer;color:#475569;font-size:14px;font-weight:700;min-height:44px;padding:10px 0}.nearby-section .nearby-practical{font-size:14px;color:#475569;margin:8px 0 0}.nearby-links{margin-top:auto;display:flex;flex-wrap:wrap;align-items:center;gap:8px 20px}.nearby-section .nearby-links a{display:inline-flex;align-items:center;min-height:44px;color:#4338ca;font-weight:700;font-size:14px;text-decoration:underline;text-underline-offset:4px}.nearby-section .nearby-links a:first-child{padding:10px 14px;border:1px solid #c7d2fe;background:#eef2ff;border-radius:12px;text-decoration:none}.nearby-section .nearby-links a:hover{color:#312e81;background:#e0e7ff}.nearby-section a:focus-visible,.nearby-section summary:focus-visible{outline:3px solid #6366f1;outline-offset:4px}.nearby-section .nearby-season{max-width:900px;margin:24px 0 0;color:#475569;font-size:14px}.nearby-credits{margin-top:16px;color:#64748b;font-size:12px}.nearby-credits summary{cursor:pointer;min-height:44px;padding:12px 0}.nearby-section .nearby-credits p{margin:6px 0 12px}.nearby-credits ul{margin:0;padding-left:20px}.nearby-credits li{margin-bottom:8px}.nearby-credits a{color:inherit;text-decoration:underline;text-underline-offset:3px}@media(max-width:650px){.nearby-grid{grid-template-columns:1fr}.nearby-section{padding:40px 20px}.nearby-card-body{padding:22px}.nearby-section .nearby-photo figcaption{padding:8px 22px}}
.pompeii-trip{margin-top:40px;padding-top:36px;border-top:1px solid #cbd5e1;scroll-margin-top:190px}.pompeii-photos{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:22px 0}.pompeii-photos .nearby-photo{border-radius:18px;overflow:hidden}.nearby-section .pompeii-plan{font-weight:700;color:#334155;max-width:880px;margin:0 0 18px}.pompeii-trip .nearby-details{max-width:880px}.pompeii-trip .nearby-practical a{color:#4338ca;text-decoration:underline}.pompeii-trip .nearby-text{max-width:850px}@media(max-width:650px){.pompeii-photos{grid-template-columns:1fr}}
</style><section id="nearby" class="nearby-section" aria-labelledby="nearby-title"><div class="nearby-wrap"><p class="nearby-eyebrow">${esc(copy.eyebrow)}</p><h2 id="nearby-title">${esc(copy.title)}</h2><p class="nearby-intro">${esc(copy.intro)}</p><div class="nearby-grid">${NEARBY_PLACES.map((place, index) => {
    const item = copy.places[index], photo = NEARBY_PHOTOS[place.id];
    return `<article class="nearby-card" data-place="${place.id}"><figure class="nearby-photo"><img src="${photo.src}" alt="${esc(copy.photoAlt[index])}" width="${photo.width}" height="${photo.height}" loading="lazy" decoding="async" /><figcaption>${esc(copy.photoAlt[index])}</figcaption></figure><div class="nearby-card-body"><h3>${esc(item.title)}</h3><p class="nearby-text">${esc(item.text)}</p><details class="nearby-details"><summary>${esc(copy.practicalLabel)}</summary><p class="nearby-practical">${esc(item.practical)}</p></details><div class="nearby-links"><a href="${esc(nearbyMap(place))}" target="_blank" rel="noopener noreferrer" aria-label="${esc(`${copy.map}: ${item.title}`)}">${esc(copy.map)} ↗</a><a href="${esc(place.source)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(`${place.id === 'arcomagno' ? copy.access : copy.source}: ${item.title}`)}">${esc(place.id === 'arcomagno' ? copy.access : copy.source)} ↗</a></div></div></article>`;
  }).join('')}</div><p class="nearby-season">${esc(copy.season)}</p><article id="pompeii" class="pompeii-trip" aria-labelledby="pompeii-title"><p class="nearby-eyebrow">${esc(pompeii.badge)}</p><h3 id="pompeii-title">${esc(pompeii.title)}</h3><p class="nearby-text">${esc(pompeii.text)}</p><div class="pompeii-photos">${POMPEII_PHOTO_IDS.map((id,index)=>{const photo=NEARBY_PHOTOS[id];return `<figure class="nearby-photo"><img src="${photo.src}" alt="${esc(pompeii.photos[index])}" width="${photo.width}" height="${photo.height}" loading="lazy" decoding="async" /><figcaption>${esc(pompeii.photos[index])}</figcaption></figure>`;}).join('')}</div><p class="pompeii-plan">${esc(pompeii.plan)}</p><details class="nearby-details"><summary>${esc(copy.practicalLabel)}</summary><p class="nearby-practical">${esc(pompeii.practical)} <a href="${POMPEII_TRAVEL}" target="_blank" rel="noopener noreferrer">${esc(pompeii.travel)} ↗</a></p></details><div class="nearby-links"><a href="${esc(POMPEII_MAP)}" target="_blank" rel="noopener noreferrer">${esc(pompeii.car)} ↗</a><a href="${POMPEII_VISIT}" target="_blank" rel="noopener noreferrer">${esc(pompeii.tickets)} ↗</a></div></article><details class="nearby-credits"><summary>${esc(copy.credits)}</summary><p>${esc(copy.photoNote)}</p><ul>${[...NEARBY_PLACES.map(place => place.id), ...POMPEII_PHOTO_IDS].map(id => {
    const photo = NEARBY_PHOTOS[id];
    return `<li><a href="${esc(photo.source)}" target="_blank" rel="noopener noreferrer">${esc(photo.title)}</a> — ${esc(photo.author)}${photo.date ? ` (${esc(photo.date)})` : ''} · <a href="${esc(photo.licenseUrl)}" target="_blank" rel="noopener noreferrer">${esc(photo.license)}</a></li>`;
  }).join('')}</ul></details></div></section>`;
}
