import { getNearbyCopy, NEARBY_PLACES, nearbyMap } from './nearby';

const esc = (text: string) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');

// Shared static content keeps the homepage, no-JS HTML and winter landing consistent.
export function renderNearby(language: string): string {
  const copy = getNearbyCopy(language);
  return `<style>
.nearby-section{padding:56px 24px;background:#f8fafc;color:#0f172a;scroll-margin-top:190px;font:16px/1.65 'Roboto',system-ui,sans-serif;overflow-wrap:anywhere}
.nearby-section *{box-sizing:border-box}.nearby-wrap{max-width:1160px;margin:auto}.nearby-section .nearby-eyebrow{color:#4338ca;font-size:12px;letter-spacing:.14em;text-transform:uppercase;font-weight:700;margin:0 0 12px}.nearby-section h2{font-family:'Playfair Display',Georgia,serif;font-size:clamp(28px,3vw,42px);line-height:1.2;margin:0 0 18px;font-weight:700;letter-spacing:-.02em}.nearby-intro{max-width:780px;color:#475569;margin:0 0 28px}.nearby-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.nearby-card{display:flex;flex-direction:column;background:white;border:1px solid #e2e8f0;border-radius:24px;padding:26px}.nearby-section .nearby-number{color:#6366f1;font-size:13px;letter-spacing:.15em;font-weight:700;margin:0 0 12px}.nearby-section h3{font-family:'Playfair Display',Georgia,serif;font-size:25px;line-height:1.25;font-weight:700;margin:0 0 14px;letter-spacing:-.02em}.nearby-section .nearby-text{margin:0 0 16px;color:#475569}.nearby-section .nearby-practical{font-size:14px;color:#64748b;margin:0 0 20px}.nearby-links{margin-top:auto;display:flex;flex-wrap:wrap;gap:4px 20px}.nearby-section .nearby-links a{display:inline-flex;align-items:center;min-height:44px;color:#4338ca;font-weight:700;font-size:14px;text-decoration:underline;text-underline-offset:4px}.nearby-section a:focus-visible{outline:3px solid #6366f1;outline-offset:4px}.nearby-section .nearby-season{max-width:900px;margin:24px 0 0;color:#475569;font-size:14px}@media(max-width:650px){.nearby-grid{grid-template-columns:1fr}.nearby-section{padding:40px 20px}.nearby-card{padding:22px}}
</style><section id="nearby" class="nearby-section" aria-labelledby="nearby-title"><div class="nearby-wrap"><p class="nearby-eyebrow">${esc(copy.eyebrow)}</p><h2 id="nearby-title">${esc(copy.title)}</h2><p class="nearby-intro">${esc(copy.intro)}</p><div class="nearby-grid">${NEARBY_PLACES.map((place, index) => {
    const item = copy.places[index];
    return `<article class="nearby-card" data-place="${place.id}"><p class="nearby-number" aria-hidden="true">0${index + 1}</p><h3>${esc(item.title)}</h3><p class="nearby-text">${esc(item.text)}</p><p class="nearby-practical">${esc(item.practical)}</p><div class="nearby-links"><a href="${esc(nearbyMap(place))}" target="_blank" rel="noopener noreferrer" aria-label="${esc(`${copy.map}: ${item.title}`)}">${esc(copy.map)} ↗</a><a href="${esc(place.source)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(`${place.id === 'arcomagno' ? copy.access : copy.source}: ${item.title}`)}">${esc(place.id === 'arcomagno' ? copy.access : copy.source)} ↗</a></div></article>`;
  }).join('')}</div><p class="nearby-season">${esc(copy.season)}</p></div></section>`;
}
