
import { Apartment, Review } from './types';

// --- ВЕРСИЯ ДАННЫХ ---
export const SITE_DATA_VERSION = 10;

// Центральный номер для связи (замените на ваш реальный номер)
export const CONTACT_INFO = {
  phone: '420774620060', // Формат: 79001234567 или 39...
  whatsappLink(text: string) {
    return `https://wa.me/${this.phone}?text=${encodeURIComponent(text)}`;
  }
};

// --- ФОТОГРАФИИ САЙТА ---
// Вы можете изменять ссылки ниже, чтобы обновить фото на сайте.
export const SITE_IMAGES = {
  heroBackground: 'https://i.postimg.cc/Dz0dHGzW/Scalea.webp', // Главное фото на первом экране
  aboutImages: [
    'https://i.postimg.cc/ZYfbNrJM/web_ready_bg.jpg',
    'https://i.postimg.cc/sXfXq0Xf/Gemini_Generated_Image_9ufx2j9ufx2j9ufx.png',
    'https://i.postimg.cc/1tTHJd0Y/unnamed.jpg',
    'https://i.postimg.cc/qv9Pq6cY/Obr%C3%A1zek_PNG_4.png'
  ], // Фото в разделе "О Скалее"
  logo: '', // Если понадобится логотип
  aboutSection: 'https://i.postimg.cc/bY72f4g5/italy-scalea-beach-pebble-sand-orig.jpg',
  guideImages: [
    'https://i.postimg.cc/XY3vV4DY/IMG-0056.png',
    'https://i.postimg.cc/rsKbh0p3/Scalea_Torre_Talao_am_Morgen.jpg',
    'https://i.postimg.cc/XNFty39Z/IMG_2859.jpg'
  ]
};

export const APARTMENTS: Apartment[] = [
  {
    id: '1',
    name: 'ScaleaStay',
    nameKey: 'apt1Name',
    description: 'Светлые и уютные апартаменты с современным ремонтом для отдыха у моря. Ближайший пляж — 600 м, около 5–8 минут пешком.',
    descriptionKey: 'apt1Desc',
    price: 'от 50€',
    beds: 4,
    distanceToSea: '600m',
    images: [
      'https://i.postimg.cc/rmgf10N5/IMG_0338.jpg',
      'https://i.postimg.cc/vBX0rgth/IMG_0349.jpg',
      'https://i.postimg.cc/fL58ctvn/IMG_0329.jpg',
      'https://i.postimg.cc/tTDB3ZNM/IMG_0355.jpg',
      'https://i.postimg.cc/DZ5xrJPr/IMG_0348.jpg',
      'https://i.postimg.cc/j5vMHw4P/IMG_0357.jpg',
      'https://i.postimg.cc/ZRjw8Bx7/IMG_0358.jpg'
    ],
    features: [
      'Кондиционер',
      'Терраса',
      'Парковка'
    ],
    featuresKeys: [
      'apt1Feature1',
      'apt1Feature2',
      'apt1Feature3'
    ]
  }
];

export const REVIEWS: Review[] = [
  { name: 'Елена', nameKey: 'rev1Name', text: 'Отличное место для отдыха. Чисто, уютно, мебель и техника новые. Расположение топовое — до набережной рукой подать, вокруг полно магазинов и ресторанов. Остались очень довольны выбором!', textKey: 'rev1Text', rating: 5 },
  { name: 'Марк', nameKey: 'rev2Name', text: 'Чисто, уютно и очень близко к пляжу. Вернемся обязательно в следующем году.', textKey: 'rev2Text', rating: 5 },
  { name: 'Ольга', nameKey: 'rev3Name', text: 'Лучшее расположение в Скалее. Старый город в пяти минутах ходьбы.', textKey: 'rev3Text', rating: 5 }
];

export const LANGUAGES = [
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿' },
];

export const TRANSLATIONS: Record<string, any> = {
  ru: {
    taTitle: 'Кому подойдут наши апартаменты',
    taItem1: 'Семьям, которые хотят отдыхать рядом с морем и жить в спокойной квартире.',
    taItem2: 'Гостям, которые приезжают в Калабрию на машине и хотят иметь парковку.',
    taItem3: 'Тем, кому важно жить в центре Скалеи, рядом с магазинами и прогулочными местами.',
    taItem4: 'Тем, кто хочет быстро покупать продукты рядом — крупный Interspar находится недалеко.',
    taItem5: 'Тем, кто хочет уточнить свободные даты напрямую через WhatsApp.',
    heroTitle: 'Уютные апартаменты у моря в Скалее «Калабрия»',
    navHome: 'Главная',
    navApartments: "Апартаменты",
    navWeather: 'Погода',
    navAbout: 'О городе',
    navContact: 'Контакты',
    navFaq: 'FAQ',
    howToGet: 'Как добраться',
    byTrain: 'На поезде',
    byTrainDesc: 'Станция Scalea-Santa Domenica Talao. Прямые поезда из Рима и Неаполя.',
    byCar: 'На машине',
    byCarDesc: 'Трасса A2 «Salerno-Reggio Calabria», съезд на Scalea.',
    byPlane: 'На самолете',
    byPlaneDesc: 'Ближайший аэропорт — Ламеция-Терме «SUF», далее 1.5 часа на поезде или авто.',
    detailedRoute: 'Подробный маршрут',
    addressLabel: 'Наш адрес',
    addressValue: '87029 Скалея, Провинция Козенца, Италия',
    close: 'Закрыть',
    routeDetails: 'Как нас найти',
    routeDetailsDesc: 'Мы находимся в самом сердце Скалеи. Если вы едете на поезде, мы можем организовать трансфер от вокзала. Если на машине — следуйте по навигатору до указанного адреса, парковка предоставляется бесплатно.',
    designCreditTitle: 'Понравился дизайн сайта?',
    designCreditBtn: 'Написать в Telegram',
    heroSubtitle: "У моря — с домашним комфортом: Wi‑Fi, газовое отопление и собственная терраса.",
    advantagesTitle: 'Наши преимущества',
    advLocation: 'Центральное расположение',
    advLocationDesc: 'Самый центр города, рядом находится большой продуктовый супермаркет и детский парк развлечений.',
    advSea: 'Близость к морю',
    advSeaDesc: 'Ближайший пляж — 600 м, около 5–8 минут пешком.',
    advRenovation: 'Современный ремонт',
    advRenovationDesc: 'Элегантный интерьер и новая мебель для вашего максимального комфорта.',
    advFamily: 'Семейный уют',
    advFamilyDesc: 'Идеально подходит для отдыха с детьми в любое время года.',
    advParking: 'Бесплатная парковка',
    advParkingDesc: 'Ваш автомобиль будет в безопасности на нашей частной парковке.',
    advSupermarket: 'Супермаркет Interspar',
    advSupermarketDesc: 'Крупный супермаркет Interspar рядом — удобно для ежедневных покупок во время отдыха.',
    bookNow: 'Забронировать',
    aboutScalea: 'О Скалее',
    aboutScaleaDesc: 'Скалея — жемчужина побережья Riviera dei Cedri в Калабрии. Здесь лазурное Тирренское море встречается с величественными горами. Наш город предлагает лучший отдых в Италии: чистейшие пляжи, старый город и аутентичную кухню.',
    ourApartments: "Апартаменты ScaleaStay",
    weather: 'Погода',
    weatherSubtitle: 'Актуальный прогноз для вашего отдыха',
    localExperience: 'Локальный опыт',
    localExperienceDesc: 'Мы расскажем, в каком ресторане самая свежая рыба, а где лучший аперитив с видом на закат.',
    flawlessService: 'Безупречный сервис',
    flawlessServiceDesc: 'AI-консьерж 24/7, трансфер из аэропорта и помощь в организации ваших идеальных каникул.',
    directBooking: 'Доступно прямое бронирование',
    waitsForYou: 'Ждет вас',
    whatsappBookingMsg: 'Здравствуйте! Я хочу забронировать ваши апартаменты в Скалее. Подскажите, пожалуйста, свободны ли даты...',
    beachDistance: 'Пляж 5–8 мин',
    acReady: 'Кондиционер',
    parkingInc: 'Парковка вкл.',
    footerCopyright: 'ScaleaStay © 2026 • Калабрийское гостеприимство',
    heroBadge: 'Скалея, Италия',
    heroWhatsappMsg: 'Здравствуйте! Я хочу забронировать ваши апартаменты в Скалее. Подскажите, пожалуйста, свободны ли даты...',
    navWhatsappMsg: 'Здравствуйте! Я хочу забронировать ваши апартаменты в Скалее. Подскажите, пожалуйста, свободны ли даты...',
    apartmentBookingMsg: 'Здравствуйте! Я хочу забронировать ваши апартаменты в Скалее. Подскажите, пожалуйста, свободны ли даты...',
    weatherToday: 'Сегодня',
    weatherError: 'Не удалось загрузить данные о погоде',
    tryAgain: 'Попробовать снова',
    online: 'В сети',
    backToTop: 'Вверх',
    beds: 'спальных мест',
    distance: 'до моря',
    features: 'Удобства',
    reviews: 'Отзывы гостей',
    contactUs: 'Связаться с нами',
    aiAssistant: 'AI Консьерж',
    aiPlaceholder: 'Спросите меня о Скалее...',
    aiGreeting: "Здравствуйте! Помогу узнать о квартире, Wi‑Fi, отоплении, пляже и магазинах рядом. Даты и стоимость подскажет владелец в WhatsApp.",
    faqTitle: 'Частые вопросы',
    faqQ1: 'Где именно находятся апартаменты и как далеко идти до моря?',
    faqA1: 'Мы находимся по адресу Via Giuseppe Saragat 11 в центральной части Скалеи. До ближайшего пляжа — 600 м, обычно около 5–8 минут пешком.',
    faqQ2: 'Какие удобства есть в квартире?',
    faqA2: "В апартаментах есть отдельная спальня, терраса, оборудованная кухня, кондиционер, газовое отопление и Wi‑Fi.",
    faqQ3: 'Есть ли у вас парковка для гостей?',
    faqA3: 'Да, конечно! Для наших гостей доступна удобная парковка на закрытой территории. Обратите внимание, что зарядных станций для электромобилей у нас пока нет.',
    faqQ4: 'Как происходит заселение и передача ключей?',
    faqA4: 'Стандартное время заезда начинается с 14:00, а выезд — до 10:00. При заселении мы встретим вас лично, передадим ключи и ответим на все вопросы. Если вам нужно другое время, просто напишите нам заранее!',
    faqQ5: 'Как забронировать апартаменты в Скалее напрямую?',
    faqA5: "Напишите в WhatsApp даты поездки и число гостей. Владелец проверит свободные даты, сообщит стоимость и объяснит, как подтвердить бронирование.",
    faqQ6: 'Как проверить свободные даты?',
    faqA6: 'Вы можете просто написать нам в WhatsApp — мы быстро ответим, свободны ли апартаменты на ваши даты.',
    faqQ7: 'Подходит ли квартира для семейного отдыха?',
    faqA7: "В апартаментах есть отдельная спальня и кухня, где можно готовить для семьи. Напишите, сколько будет взрослых и детей, — уточним спальные места и ваши пожелания.",
    faqQ8: 'Есть ли рядом магазины?',
    faqA8: 'Да, рядом с апартаментами находится крупный супермаркет Interspar, удобно для ежедневных покупок во время отдыха.',
    guideTitle: 'Гид по Скалее',
    guideSubtitle: "Куда сходить и что посмотреть",
    guidePlace1: 'Ресторан «La Perla del Tirreno»',
    guideDesc1: "Идея для ужина с рыбой и морепродуктами.",
    guidePlace2: 'Башня Торре Талао',
    guideDesc2: "Один из символов Скалеи, примерно в 12 минутах пешком от апартаментов.",
    guidePlace3: 'Старый город',
    guideDesc3: 'Узкие улочки, где замирает время. Идеально для вечерней прогулки.',
    callUs: 'Позвонить',
    priceFrom: 'от',
    meters: 'м',
    apt1Name: 'ScaleaStay',
    apt1Desc: "Апартаменты с одной спальней и собственной террасой. Готовьте на оборудованной кухне, отдыхайте после пляжа и выбирайте удобный для вас срок поездки.",
    apt1Feature1: 'Кондиционер',
    apt1Feature2: 'Терраса',
    apt1Feature3: 'Парковка',
    rev1Name: 'Елена',
    rev1Text: 'Отличное место для отдыха. Чисто, уютно, мебель и техника новые. Расположение топовое — до набережной рукой подать, вокруг полно магазинов и ресторанов. Остались очень довольны выбором!',
    rev2Name: 'Марк',
    rev2Text: 'Чисто, уютно и очень близко к пляжу. Вернемся обязательно в следующем году.',
    rev3Name: 'Ольга',
    rev3Text: 'Лучшее расположение в Скалее. Старый город в пяти минутах ходьбы.',
    directBookTitle: "Договоритесь о поездке напрямую",
    directBookItem1: "Обсудите даты и пожелания с владельцем",
    directBookItem2: "Узнайте стоимость и условия до бронирования",
    directBookItem3: "Задайте вопросы о квартире и приезде в WhatsApp",
    directBookItem4: 'Проверенный объект (мы есть на Booking и Airbnb)',
    directBookItem5: 'Быстрое подтверждение после проверки свободных дат',
    heroCtaHint: 'Напишите в WhatsApp — проверим свободные даты',
  },
  en: {
    taTitle: 'Who our apartments are ideal for',
    taItem1: 'Families who want to stay close to the sea in a comfortable apartment.',
    taItem2: 'Guests travelling to Calabria by car who need parking.',
    taItem3: 'Travellers who want to stay in the centre of Scalea, close to shops and walking areas.',
    taItem4: 'Guests who want easy daily groceries — a large Interspar supermarket is nearby.',
    taItem5: 'Guests who prefer to check availability directly via WhatsApp.',
    heroTitle: 'Modern holiday apartment by the sea in Scalea',
    navHome: 'Home',
    navApartments: "Apartment",
    navWeather: 'Weather',
    navAbout: 'About',
    navContact: 'Contact',
    navFaq: 'FAQ',
    howToGet: 'How to get here',
    byTrain: 'By Train',
    byTrainDesc: 'Scalea-Santa Domenica Talao station. Direct trains from Rome and Naples.',
    byCar: 'By Car',
    byCarDesc: 'A2 highway (Salerno-Reggio Calabria), exit to Scalea.',
    byPlane: 'By Plane',
    byPlaneDesc: 'Nearest airport is Lamezia Terme (SUF), then 1.5 hours by train or car.',
    detailedRoute: 'Detailed Route',
    addressLabel: 'Our Address',
    addressValue: '87029 Scalea, Province of Cosenza, Italy',
    close: 'Close',
    routeDetails: 'How to find us',
    routeDetailsDesc: 'We are located in the heart of Scalea. If you arrive by train, we can arrange a transfer from the station. If by car, follow the GPS to the specified address; free parking is provided.',
    designCreditTitle: 'Like the website design?',
    designCreditBtn: 'Write on Telegram',
    heroSubtitle: "Feel at home by the sea, with Wi‑Fi, gas heating and your own terrace.",
    advantagesTitle: 'Our Advantages',
    advLocation: 'Central Location',
    advLocationDesc: 'Right in the city center, close to a large grocery supermarket and a children\'s amusement park.',
    advSea: 'Near the Sea',
    advSeaDesc: 'The nearest beach is 600 m away, about a 5–8 minute walk.',
    advRenovation: 'Modern Renovation',
    advRenovationDesc: 'Elegant interior and new furniture for your maximum comfort.',
    advFamily: 'Family Comfort',
    advFamilyDesc: 'Perfect for vacations with children at any time of the year.',
    advParking: 'Free Parking',
    advParkingDesc: 'Your car will be safe in our private parking lot.',
    advSupermarket: 'Interspar Supermarket',
    advSupermarketDesc: 'A large Interspar supermarket is nearby — convenient for daily groceries during your stay.',
    bookNow: 'Book Now',
    aboutScalea: 'About Scalea',
    aboutScaleaDesc: 'Scalea is the gem of the Riviera dei Cedri in Calabria, where the azure Tyrrhenian Sea meets majestic mountains. Experience the best stay in Italy: pristine beaches, old town charm, and authentic cuisine.',
    ourApartments: "Your ScaleaStay apartment",
    weather: 'Weather',
    weatherSubtitle: 'Current forecast for your vacation',
    localExperience: 'Local Experience',
    localExperienceDesc: 'We will tell you which restaurant has the freshest fish and where the best sunset aperitif is.',
    flawlessService: 'Flawless Service',
    flawlessServiceDesc: '24/7 AI concierge, airport transfer, and help organizing your perfect vacation.',
    directBooking: 'Direct Booking Available',
    waitsForYou: 'Waits for you',
    whatsappBookingMsg: 'Hello! I would like to book your apartment in Scalea. Please let me know if the dates are available...',
    beachDistance: 'Beach 5–8 min',
    acReady: 'Air Conditioning',
    parkingInc: 'Parking Included',
    footerCopyright: 'ScaleaStay © 2026 • Calabrian Hospitality',
    heroBadge: 'Scalea, Italy',
    heroWhatsappMsg: 'Hello! I would like to book your apartment in Scalea. Please let me know if the dates are available...',
    navWhatsappMsg: 'Hello! I would like to book your apartment in Scalea. Please let me know if the dates are available...',
    apartmentBookingMsg: 'Hello! I would like to book your apartment in Scalea. Please let me know if the dates are available...',
    weatherToday: 'Today',
    weatherError: 'Failed to load weather data',
    tryAgain: 'Try again',
    online: 'Online',
    backToTop: 'Back to top',
    beds: 'beds',
    distance: 'to the sea',
    features: 'Amenities',
    reviews: 'Guest Reviews',
    contactUs: 'Contact Us',
    aiAssistant: 'AI Concierge',
    aiPlaceholder: 'Ask me about Scalea...',
    aiGreeting: "Hello! I can help with the apartment, Wi‑Fi, heating, beach and nearby shops. For dates and prices, I can direct you to the owner on WhatsApp.",
    faqTitle: 'FAQ',
    faqQ1: 'Where exactly are the apartments located and how far is the sea?',
    faqA1: 'We are located at Via Giuseppe Saragat 11 in central Scalea. The nearest beach is 600 m away, usually about a 5–8 minute walk.',
    faqQ2: 'What amenities are available in the apartment?',
    faqA2: "The apartment has a separate bedroom, terrace, equipped kitchen, air conditioning, gas heating and Wi‑Fi.",
    faqQ3: 'Do you have a parking space for guests?',
    faqA3: 'Yes, absolutely! Feel free to use our guest parking located in a closed, private territory. Please note that we do not have EV charging stations at the moment.',
    faqQ4: 'How does check-in and key handover work?',
    faqA4: 'Standard check-in starts at 14:00, and check-out is until 10:00. We will meet you personally upon arrival, hand over the keys, and answer any questions. If you need a different time, just let us know in advance!',
    faqQ5: 'How can I book the apartments in Scalea directly?',
    faqA5: "Send your travel dates and number of guests on WhatsApp. The owner will check availability, share the price and explain how to confirm your booking.",
    faqQ6: 'Как проверить свободные даты?',
    faqA6: 'Вы можете просто написать нам в WhatsApp — мы быстро ответим, свободны ли апартаменты на ваши даты.',
    faqQ7: 'Is the apartment suitable for a family vacation?',
    faqA7: "There is a separate bedroom and a kitchen for preparing family meals. Tell us how many adults and children are travelling so we can discuss sleeping arrangements and your needs.",
    guideTitle: 'Scalea Guide',
    guideSubtitle: "Places to explore during your stay",
    guidePlace1: 'Restaurant "La Perla del Tirreno"',
    guideDesc1: "An option for a fish or seafood dinner.",
    guidePlace2: 'Torre Talao',
    guideDesc2: "One of Scalea’s landmarks, about a 12-minute walk from the apartment.",
    guidePlace3: 'Old Town',
    guideDesc3: 'Narrow streets where time stands still. Perfect for an evening walk.',
    callUs: 'Call Us',
    priceFrom: 'from',
    meters: 'm',
    apt1Name: 'ScaleaStay',
    apt1Desc: "A one-bedroom apartment with your own terrace. Prepare meals in the equipped kitchen, unwind after the beach and stay for a short break or a longer visit.",
    apt1Feature1: 'Air Conditioning',
    apt1Feature2: 'Terrace',
    apt1Feature3: 'Parking',
    rev1Name: 'Elena',
    rev1Text: 'Great place to stay. Clean, cozy, new furniture and appliances. Top location — just a stone\'s throw from the promenade, surrounded by shops and restaurants. Very happy with our choice!',
    rev2Name: 'Mark',
    rev2Text: 'Clean, cozy and very close to the beach. We will definitely come back next year.',
    rev3Name: 'Olga',
    rev3Text: 'Best location in Scalea. Old town is a five-minute walk away.',
    directBookTitle: "Plan your stay directly with the owner",
    directBookItem1: "Discuss your dates and preferences with the owner",
    directBookItem2: "Check the price and terms before booking",
    directBookItem3: "Ask about the apartment and your arrival on WhatsApp",
    directBookItem4: 'Verified property (listed on Booking & Airbnb)',
    directBookItem5: 'Fast confirmation after checking availability',
    heroCtaHint: 'Message us on WhatsApp to check availability',
  },
  it: {
    taTitle: 'Per chi sono ideali i nostri appartamenti',
    taItem1: 'Famiglie che vogliono soggiornare vicino al mare in un appartamento confortevole.',
    taItem2: 'Ospiti che arrivano in Calabria in auto e hanno bisogno di parcheggio.',
    taItem3: 'Viaggiatori che vogliono soggiornare nel centro di Scalea, vicino a negozi e zone per passeggiare.',
    taItem4: 'Ospiti che vogliono fare la spesa facilmente ogni giorno — un grande supermercato Interspar è nelle vicinanze.',
    taItem5: 'Ospiti che preferiscono verificare la disponibilità direttamente su WhatsApp.',
    heroTitle: 'Appartamento moderno vicino al mare a Scalea',
    navHome: 'Home',
    navApartments: "Appartamento",
    navWeather: 'Meteo',
    navAbout: 'La Città',
    navContact: 'Contatti',
    navFaq: 'FAQ',
    howToGet: 'Come arrivare',
    byTrain: 'In treno',
    byTrainDesc: 'Stazione Scalea-Santa Domenica Talao. Treni diretti da Roma e Napoli.',
    byCar: 'In auto',
    byCarDesc: 'Autostrada A2 (Salerno-Reggio Calabria), uscita Scalea.',
    byPlane: 'In aereo',
    byPlaneDesc: 'L\'aeroporto più vicino è Lamezia Terme (SUF), poi 1,5 ore in treno o auto.',
    detailedRoute: 'Percorso dettagliato',
    addressLabel: 'Il nostro indirizzo',
    addressValue: '87029 Scalea, Provincia di Cosenza, Italia',
    close: 'Chiudi',
    routeDetails: 'Come trovarci',
    routeDetailsDesc: 'Siamo nel cuore di Scalea. Se arrivi in treno, possiamo organizzare un trasferimento. Se in auto, segui il GPS; parcheggio gratuito disponibile.',
    designCreditTitle: 'Ti piace il design del sito?',
    designCreditBtn: 'Scrivi su Telegram',
    heroSubtitle: "Al mare, con il comfort di casa: Wi‑Fi, riscaldamento a gas e una terrazza tutta per te.",
    advantagesTitle: 'I nostri vantaggi',
    advLocation: 'Posizione centrale',
    advLocationDesc: 'In pieno centro città, vicino a un grande supermercato e a un parco divertimenti per bambini.',
    advSea: 'Vicino al mare',
    advSeaDesc: 'La spiaggia più vicina dista 600 m, circa 5–8 minuti a piedi.',
    advRenovation: 'Ristrutturazione moderna',
    advRenovationDesc: 'Interni eleganti e mobili nuovi per il massimo comfort.',
    advFamily: 'Comfort familiare',
    advFamilyDesc: 'Perfetto per vacanze con bambini in qualsiasi periodo dell\'anno.',
    advParking: 'Parcheggio gratuito',
    advParkingDesc: 'La tua auto sarà al sicuro nel nostro parcheggio privato.',
    advSupermarket: 'Supermercato Interspar',
    advSupermarketDesc: 'Un grande supermercato Interspar si trova nelle vicinanze — comodo per la spesa quotidiana durante il soggiorno.',
    bookNow: 'Prenota ora',
    aboutScalea: 'Scopri Scalea',
    aboutScaleaDesc: 'Scalea è la perla della Riviera dei Cedri in Calabria, dove il mare Tirreno incontra le maestose montagne. Scopri il miglior soggiorno in Italia: spiagge incontaminate, fascino del centro storico e cucina autentica.',
    ourApartments: "Il tuo appartamento ScaleaStay",
    weather: 'Meteo',
    weatherSubtitle: 'Previsioni attuali per la tua vacanza',
    localExperience: 'Esperienza Locale',
    localExperienceDesc: 'Ti diremo quale ristorante ha il pesce più fresco e dove si trova il miglior aperitivo al tramonto.',
    flawlessService: 'Servizio Impeccabile',
    flawlessServiceDesc: 'Concierge AI 24/7, trasferimento aeroportuale e aiuto per organizzare la tua vacanza perfetta.',
    directBooking: 'Prenotazione diretta disponibile',
    waitsForYou: 'Ti aspetta',
    whatsappBookingMsg: 'Buongiorno! Vorrei prenotare il vostro appartamento a Scalea. Sono libere le date...',
    beachDistance: 'Spiaggia 5–8 min',
    acReady: 'Aria Condizionata',
    parkingInc: 'Parcheggio incluso',
    footerCopyright: 'ScaleaStay © 2026 • Ospitalità Calabrese',
    heroBadge: 'Scalea, Italia',
    heroWhatsappMsg: 'Buongiorno! Vorrei prenotare il vostro appartamento a Scalea. Sono libere le date...',
    navWhatsappMsg: 'Buongiorno! Vorrei prenotare il vostro appartamento a Scalea. Sono libere le date...',
    apartmentBookingMsg: 'Buongiorno! Vorrei prenotare il vostro appartamento a Scalea. Sono libere le date...',
    weatherToday: 'Oggi',
    weatherError: 'Impossibile caricare i dati meteo',
    tryAgain: 'Riprova',
    online: 'Online',
    backToTop: 'Torna su',
    beds: 'posti letto',
    distance: 'dal mare',
    features: 'Servizi',
    reviews: 'Recensioni degli ospiti',
    contactUs: 'Contattaci',
    aiAssistant: 'AI Concierge',
    aiPlaceholder: 'Chiedimi di Scalea...',
    aiGreeting: "Ciao! Posso aiutarti con informazioni su appartamento, Wi‑Fi, riscaldamento, spiaggia e negozi vicini. Per date e prezzi, ti indirizzo al proprietario su WhatsApp.",
    faqTitle: 'Domande Frequenti',
    faqQ1: 'Dove si trovano esattamente gli appartamenti e quanto dista il mare?',
    faqA1: 'Ci troviamo in Via Giuseppe Saragat 11, nella zona centrale di Scalea. La spiaggia più vicina dista 600 m, normalmente circa 5–8 minuti a piedi.',
    faqQ2: 'Quali servizi ci sono nell\'appartamento?',
    faqA2: "L’appartamento dispone di una camera da letto separata, terrazza, cucina attrezzata, aria condizionata, riscaldamento a gas e Wi‑Fi.",
    faqQ3: 'Avete un parcheggio per gli ospiti?',
    faqA3: 'Certamente! Per i nostri ospiti è disponibile un parcheggio in un\'area privata recintata. Vi preghiamo di notare che al momento non disponiamo di stazioni di ricarica per veicoli elettrici.',
    faqQ4: 'Come funziona il check-in e la consegna delle chiavi?',
    faqA4: 'L\'orario di check-in standard è dalle 14:00, mentre il check-out è entro le 10:00. Al vostro arrivo vi accoglieremo personalmente, vi consegneremo le chiavi e risponderemo a tutte le vostre domande. Se avete bisogno di orari flessibili, fatecelo sapere in anticipo!',
    faqQ5: 'Come posso prenotare un appartamento a Scalea direttamente?',
    faqA5: "Invia le date e il numero di ospiti su WhatsApp. Il proprietario verificherà la disponibilità, ti comunicherà il prezzo e ti spiegherà come confermare la prenotazione.",
    faqQ6: 'Как проверить свободные даты?',
    faqA6: 'Вы можете просто написать нам в WhatsApp — мы быстро ответим, свободны ли апартаменты на ваши даты.',
    faqQ7: "L'appartamento è adatto per una vacanza in famiglia?",
    faqA7: "Ci sono una camera da letto separata e una cucina per preparare i pasti in famiglia. Indica quanti adulti e bambini viaggeranno: concorderemo la sistemazione per dormire e le tue esigenze.",
    guideTitle: 'Guida di Scalea',
    guideSubtitle: "Idee per le tue passeggiate a Scalea",
    guidePlace1: 'Ristorante "La Perla del Tirreno"',
    guideDesc1: "Un’idea per una cena a base di pesce e frutti di mare.",
    guidePlace2: 'Torre Talao',
    guideDesc2: "Uno dei simboli di Scalea, a circa 12 minuti a piedi dall’appartamento.",
    guidePlace3: 'Centro Storico',
    guideDesc3: 'Strette stradine dove il tempo si ferma. Perfetto per una passeggiata serale.',
    callUs: 'Chiamaci',
    priceFrom: 'da',
    meters: 'm',
    apt1Name: 'ScaleaStay',
    apt1Desc: "Un appartamento con una camera da letto e una terrazza tutta per te. Prepara i pasti nella cucina attrezzata, rilassati dopo la spiaggia e scegli tra una breve vacanza e un soggiorno più lungo.",
    apt1Feature1: 'Aria Condizionata',
    apt1Feature2: 'Terrazza',
    apt1Feature3: 'Parcheggio',
    rev1Name: 'Elena',
    rev1Text: 'Ottimo posto dove stare. Pulito, accogliente, mobili ed elettrodomestici nuovi. Posizione eccellente — a due passi dal lungomare, circondato da negozi e ristoranti. Molto soddisfatti della scelta!',
    rev2Name: 'Mark',
    rev2Text: 'Pulito, accogliente e molto vicino alla spiaggia. Torneremo sicuramente l\'anno prossimo.',
    rev3Name: 'Olga',
    rev3Text: 'La migliore posizione a Scalea. Il centro storico è a cinque minuti a piedi.',
    directBookTitle: "Organizza il soggiorno con il proprietario",
    directBookItem1: "Parla delle date e delle tue esigenze con il proprietario",
    directBookItem2: "Conosci prezzo e condizioni prima di prenotare",
    directBookItem3: "Chiedi informazioni su appartamento e arrivo via WhatsApp",
    directBookItem4: 'Struttura verificata (presente su Booking e Airbnb)',
    directBookItem5: 'Conferma rapida dopo aver verificato la disponibilità',
    heroCtaHint: 'Scrivici su WhatsApp per verificare la disponibilità',
  },
  de: {
    taTitle: 'Für wen unsere Apartments ideal sind',
    taItem1: 'Für Familien, die nah am Meer in einem komfortablen Apartment wohnen möchten.',
    taItem2: 'Für Gäste, die mit dem Auto nach Kalabrien reisen und Parkmöglichkeiten benötigen.',
    taItem3: 'Für Reisende, die im Zentrum von Scalea wohnen möchten, in der Nähe von Geschäften und Spazierwegen.',
    taItem4: 'Für Gäste, die bequem einkaufen möchten — ein großer Interspar-Supermarkt befindet sich in der Nähe.',
    taItem5: 'Für Gäste, die die Verfügbarkeit direkt über WhatsApp prüfen möchten.',
    heroTitle: 'Moderne Ferienwohnung am Meer in Scalea',
    navHome: 'Startseite',
    navApartments: "Ferienwohnung",
    navWeather: 'Wetter',
    navAbout: 'Über Scalea',
    navContact: 'Kontakt',
    navFaq: 'FAQ',
    howToGet: 'Anreise',
    byTrain: 'Mit dem Zug',
    byTrainDesc: 'Bahnhof Scalea-Santa Domenica Talao. Direktzüge von Rom und Neapel.',
    byCar: 'Mit dem Auto',
    byCarDesc: 'Autobahn A2 (Salerno-Reggio Calabria), Ausfahrt Scalea.',
    byPlane: 'Mit dem Flugzeug',
    byPlaneDesc: 'Der nächste Flughafen ist Lamezia Terme (SUF), danach 1,5 Stunden mit dem Zug oder Auto.',
    detailedRoute: 'Detaillierte Route',
    addressLabel: 'Unsere Adresse',
    addressValue: '87029 Scalea, Provinz Cosenza, Italien',
    close: 'Schließen',
    routeDetails: 'So finden Sie uns',
    routeDetailsDesc: 'Wir befinden uns im Herzen von Scalea. Bei Anreise mit dem Zug organisieren wir gerne einen Transfer. Bei Anreise mit dem Auto folgen Sie dem GPS; kostenlose Parkplätze sind vorhanden.',
    designCreditTitle: 'Gefällt Ihnen das Website-Design?',
    designCreditBtn: 'Auf Telegram schreiben',
    heroSubtitle: "Am Meer wie zu Hause: mit WLAN, Gasheizung und eigener Terrasse.",
    advantagesTitle: 'Ihre Vorteile',
    advLocation: 'Zentrale Lage',
    advLocationDesc: 'Direkt im Stadtzentrum, in der Nähe eines großen Supermarkts und eines Vergnügungsparks für Kinder.',
    advSea: 'Meeresnähe',
    advSeaDesc: 'Der nächste Strand ist 600 m entfernt, etwa 5–8 Gehminuten.',
    advRenovation: 'Moderne Renovierung',
    advRenovationDesc: 'Elegantes Interieur und neue Möbel für Ihren maximalen Komfort.',
    advFamily: 'Familienkomfort',
    advFamilyDesc: 'Perfekt für einen Urlaub mit Kindern zu jeder Jahreszeit.',
    advParking: 'Kostenlose Parkplätze',
    advParkingDesc: 'Ihr Auto steht sicher auf unserem Privatparkplatz.',
    advSupermarket: 'Interspar Supermarkt',
    advSupermarketDesc: 'Ein großer Interspar-Supermarkt befindet sich in der Nähe — praktisch für tägliche Einkäufe während des Aufenthalts.',
    bookNow: 'Jetzt buchen',
    aboutScalea: 'Über Scalea',
    aboutScaleaDesc: 'Scalea ist eine der ältesten Städte Kalabriens, wo das azurblaue Meer auf majestätische Berge trifft. Hier finden Sie kristallklare Strände, enge Gassen der Altstadt und authentische italienische Küche.',
    ourApartments: "Ihre Ferienwohnung ScaleaStay",
    weather: 'Wetter',
    weatherSubtitle: 'Aktuelle Vorhersage für Ihren Urlaub',
    localExperience: 'Insider-Tipps',
    localExperienceDesc: 'Wir verraten Ihnen, in welchem Restaurant es den frischesten Fisch gibt und wo Sie den besten Aperitif bei Sonnenuntergang genießen können.',
    flawlessService: 'Erstklassiger Service',
    flawlessServiceDesc: '24/7 KI-Concierge, Flughafentransfer und Hilfe bei der Organisation Ihres perfekten Urlaubs.',
    directBooking: 'Direktbuchung verfügbar',
    waitsForYou: 'Wartet auf Sie',
    whatsappBookingMsg: 'Hallo! Ich würde gerne Ihr Apartment in Scalea buchen. Sind die Termine frei...',
    beachDistance: 'Strand 5–8 Min.',
    acReady: 'Klimaanlage',
    parkingInc: 'Inkl. Parkplatz',
    footerCopyright: 'ScaleaStay © 2026 • Kalabrische Gastfreundschaft',
    heroBadge: 'Scalea, Italien',
    heroWhatsappMsg: 'Hallo! Ich würde gerne Ihr Apartment in Scalea buchen. Sind die Termine frei...',
    navWhatsappMsg: 'Hallo! Ich würde gerne Ihr Apartment in Scalea buchen. Sind die Termine frei...',
    apartmentBookingMsg: 'Hallo! Ich würde gerne Ihr Apartment in Scalea buchen. Sind die Termine frei...',
    weatherToday: 'Heute',
    weatherError: 'Wetterdaten konnten nicht geladen werden',
    tryAgain: 'Erneut versuchen',
    online: 'Online',
    backToTop: 'Nach oben',
    beds: 'Schlafplätze',
    distance: 'zum Meer',
    features: 'Ausstattung',
    reviews: 'Gästebewertungen',
    contactUs: 'Kontaktieren Sie uns',
    aiAssistant: 'KI-Concierge',
    aiPlaceholder: 'Fragen Sie mich nach Scalea...',
    aiGreeting: "Hallo! Ich helfe bei Fragen zur Wohnung, WLAN, Heizung, Strand und Geschäften in der Nähe. Für Termine und Preise leite ich Sie zum Eigentümer auf WhatsApp weiter.",
    faqTitle: 'Häufig gestellte Fragen',
    faqQ1: 'Wo genau befinden sich die Apartments und wie weit ist das Meer entfernt?',
    faqA1: 'Wir befinden uns in der Via Giuseppe Saragat 11 im zentralen Teil von Scalea. Der nächste Strand ist 600 m entfernt, normalerweise etwa 5–8 Gehminuten.',
    faqQ2: 'Welche Ausstattung gibt es in der Wohnung?',
    faqA2: "Die Ferienwohnung bietet ein separates Schlafzimmer, Terrasse, ausgestattete Küche, Klimaanlage, Gasheizung und WLAN.",
    faqQ3: 'Gibt es einen Parkplatz für Gäste?',
    faqA3: 'Ja, absolut! Unseren Gästen steht ein Parkplatz auf einem geschlossenen Privatgelände zur Verfügung. Bitte beachten Sie, dass wir derzeit keine Ladestationen für Elektroautos haben.',
    faqQ4: 'Wie funktionieren Check-in und Schlüsselübergabe?',
    faqA4: 'Der Standard-Check-in beginnt um 14:00 Uhr, der Check-out ist bis 10:00 Uhr. Wir begrüßen Sie bei der Ankunft persönlich, übergeben Ihnen die Schlüssel und beantworten alle Fragen. Wenn Sie eine andere Zeit benötigen, sagen Sie uns einfach vorher Bescheid!',
    faqQ5: 'Wie kann ich ein Apartment in Scalea direkt buchen?',
    faqA5: "Senden Sie Ihre Reisedaten und die Gästezahl per WhatsApp. Der Eigentümer prüft die Verfügbarkeit, nennt den Preis und erklärt die Buchungsbestätigung.",
    faqQ6: 'Как проверить свободные даты?',
    faqA6: 'Вы можете просто написать нам в WhatsApp — мы быстро ответим, свободны ли апартаменты на ваши даты.',
    faqQ7: 'Ist die Wohnung für einen Familienurlaub geeignet?',
    faqA7: "Ein separates Schlafzimmer und eine Küche für gemeinsame Mahlzeiten sind vorhanden. Teilen Sie uns die Anzahl der Erwachsenen und Kinder mit, damit wir Schlafplätze und Wünsche besprechen können.",
    guideTitle: 'Scalea Reiseführer',
    guideSubtitle: "Ausflugsziele für Ihren Aufenthalt",
    guidePlace1: 'Restaurant "La Perla del Tirreno"',
    guideDesc1: "Eine Möglichkeit für ein Abendessen mit Fisch und Meeresfrüchten.",
    guidePlace2: 'Torre Talao',
    guideDesc2: "Ein Wahrzeichen von Scalea, etwa 12 Gehminuten von der Ferienwohnung entfernt.",
    guidePlace3: 'Altstadt',
    guideDesc3: 'Schmale Gassen, in denen die Zeit stehen bleibt. Perfekt für einen Abendspaziergang.',
    callUs: 'Rufen Sie uns an',
    priceFrom: 'ab',
    meters: 'm',
    apt1Name: 'ScaleaStay',
    apt1Desc: "Eine Ferienwohnung mit einem Schlafzimmer und eigener Terrasse. Kochen Sie in der ausgestatteten Küche, entspannen Sie nach dem Strandbesuch und bleiben Sie für einen Kurzurlaub oder länger.",
    apt1Feature1: 'Klimaanlage',
    apt1Feature2: 'Terrasse',
    apt1Feature3: 'Parkplatz',
    rev1Name: 'Elena',
    rev1Text: 'Toller Ort zum Übernachten. Sauber, gemütlich, neue Möbel und Geräte. Top-Lage — nur einen Katzensprung von der Promenade entfernt, umgeben von Geschäften und Restaurants. Sehr zufrieden mit unserer Wahl!',
    rev2Name: 'Mark',
    rev2Text: 'Sauber, gemütlich und sehr nah am Strand. Wir kommen nächstes Jahr auf jeden Fall wieder.',
    rev3Name: 'Olga',
    rev3Text: 'Beste Lage in Scalea. Die Altstadt ist in fünf Minuten zu Fuß erreichbar.',
    directBookTitle: "Planen Sie direkt mit dem Eigentümer",
    directBookItem1: "Besprechen Sie Reisedaten und Wünsche mit dem Eigentümer",
    directBookItem2: "Klären Sie Preis und Bedingungen vor der Buchung",
    directBookItem3: "Fragen Sie per WhatsApp nach Wohnung und Anreise",
    directBookItem4: 'Verifizierte Unterkunft (gelistet auf Booking & Airbnb)',
    directBookItem5: 'Schnelle Bestätigung nach Überprüfung der Verfügbarkeit',
    heroCtaHint: 'Schreiben Sie uns auf WhatsApp, um die Verfügbarkeit zu prüfen',
  },
  cs: {
    taTitle: 'Pro koho jsou naše apartmány ideální',
    taItem1: 'Pro rodiny, které chtějí bydlet blízko moře v pohodlném apartmánu.',
    taItem2: 'Pro hosty, kteří přijíždějí do Kalábrie autem a potřebují parkování.',
    taItem3: 'Pro cestovatele, kteří chtějí bydlet v centru Scalei, blízko obchodů a míst na procházky.',
    taItem4: 'Pro hosty, kteří chtějí pohodlně nakupovat potraviny — velký supermarket Interspar je nedaleko.',
    taItem5: 'Pro hosty, kteří chtějí ověřit dostupnost přímo přes WhatsApp.',
    heroTitle: 'Moderní apartmán u moře ve Scalee',
    navHome: 'Domů',
    navApartments: "Apartmán",
    navWeather: 'Počasí',
    navAbout: 'O Scalee',
    navContact: 'Kontakt',
    navFaq: 'FAQ',
    howToGet: 'Jak se k nám dostat',
    byTrain: 'Vlakem',
    byTrainDesc: 'Stanice Scalea-Santa Domenica Talao. Přímé vlaky z Říma a Neapole.',
    byCar: 'Autem',
    byCarDesc: 'Dálnice A2 (Salerno-Reggio Calabria), sjezd na Scaleu.',
    byPlane: 'Letecky',
    byPlaneDesc: 'Nejbližší letiště je Lamezia Terme (SUF), poté 1,5 hodiny vlakem nebo autem.',
    detailedRoute: 'Podrobná trasa',
    addressLabel: 'Naše adresa',
    addressValue: '87029 Scalea, Provincie Cosenza, Itálie',
    close: 'Zavřít',
    routeDetails: 'Jak nás najdete',
    routeDetailsDesc: 'Nacházíme se v srdci Scaley. Pokud přijedete vlakem, můžeme zajistit transfer. Pokud autem, sledujte GPS; parkování je zdarma.',
    designCreditTitle: 'Líbí se vám design webu?',
    designCreditBtn: 'Napište na Telegram',
    heroSubtitle: "U moře jako doma: Wi‑Fi, plynové topení a vlastní terasa.",
    advantagesTitle: 'Naše výhody',
    advLocation: 'Centrální poloha',
    advLocationDesc: 'Přímo v centru města, v blízkosti velkého supermarketu a dětského zábavního parku.',
    advSea: 'Blízkost moře',
    advSeaDesc: 'Nejbližší pláž je 600 m daleko, přibližně 5–8 minut pěšky.',
    advRenovation: 'Moderní rekonstrukce',
    advRenovationDesc: 'Elegantní interiér a nový nábytek pro váš maximální komfort.',
    advFamily: 'Rodinné pohodlí',
    advFamilyDesc: 'Ideální pro dovolenou s dětmi v kteroukoli roční dobu.',
    advParking: 'Parkování zdarma',
    advParkingDesc: 'Vaše auto bude v bezpečí na našem soukromém parkovišti.',
    advSupermarket: 'Supermarket Interspar',
    advSupermarketDesc: 'Velký supermarket Interspar je nedaleko — pohodlné pro každodenní nákupy během pobytu.',
    bookNow: 'Rezervovat',
    aboutScalea: 'O Scalee',
    aboutScaleaDesc: 'Scalea je jedno z nejstarších měst v Kalábrii, kde se azurové moře setkává s majestátními horami. Najdete zde křišťálově čisté pláže, úzké uličky starého města a autentickou italskou kuchyni.',
    ourApartments: "Váš apartmán ScaleaStay",
    weather: 'Počasí',
    weatherSubtitle: 'Aktuální předpověď pro vaši dovolenou',
    localExperience: 'Místní zážitky',
    localExperienceDesc: 'Řekneme vám, která restaurace má nejčerstvější ryby a kde je nejlepší aperitiv při západu slunce.',
    flawlessService: 'Bezchybný servis',
    flawlessServiceDesc: '24/7 AI concierge, letištní transfer a pomoc s organizací vaší dokonalé dovolené.',
    directBooking: 'Možnost přímé rezervace',
    waitsForYou: 'Čeká na vás',
    whatsappBookingMsg: 'Dobrý den! Rád bych si rezervoval váš apartmán ve Scalea. Jsou termíny volné...',
    beachDistance: 'Pláž 5–8 min',
    acReady: 'Klimatizace',
    parkingInc: 'Parkování v ceně',
    footerCopyright: 'ScaleaStay © 2026 • Kalábrijská pohostinnost',
    heroBadge: 'Scalea, Itálie',
    heroWhatsappMsg: 'Dobrý den! Rád bych si rezervoval váš apartmán ve Scalea. Jsou termíny volné...',
    navWhatsappMsg: 'Dobrý den! Rád bych si rezervoval váš apartmán ve Scalea. Jsou termíny volné...',
    apartmentBookingMsg: 'Dobrý den! Rád bych si rezervoval váš apartmán ve Scalea. Jsou termíny volné...',
    weatherToday: 'Dnes',
    weatherError: 'Nepodařilo se načíst údaje o počasí',
    tryAgain: 'Zkusit znovu',
    online: 'Online',
    backToTop: 'Nahoru',
    beds: 'lůžek',
    distance: 'k moři',
    features: 'Vybavení',
    reviews: 'Recenze hostů',
    contactUs: 'Kontaktujte nás',
    aiAssistant: 'AI Concierge',
    aiPlaceholder: 'Zeptejte se mě na Scaleu...',
    aiGreeting: "Dobrý den! Pomohu s dotazy na apartmán, Wi‑Fi, topení, pláž a blízké obchody. Pro termíny a ceny vás odkážu na majitele přes WhatsApp.",
    faqTitle: 'Časté dotazy',
    faqQ1: 'Kde přesně se apartmány nacházejí a jak daleko je to k moři?',
    faqA1: 'Nacházíme se na adrese Via Giuseppe Saragat 11 v centrální části města Scalea. Nejbližší pláž je 600 m daleko, obvykle přibližně 5–8 minut pěšky.',
    faqQ2: 'Jaké je vybavení v apartmánu?',
    faqA2: "Apartmán má samostatnou ložnici, terasu, vybavenou kuchyň, klimatizaci, plynové topení a Wi‑Fi.",
    faqQ3: 'Máte pro hosty parkování?',
    faqA3: 'Ano, samozřejmě! Pro naše hosty je k dispozici parkování v uzavřeném areálu. Upozorňujeme, že v současné době nemáme nabíjecí stanice pro elektromobily.',
    faqQ4: 'Jak probíhá příjezd a předání klíčů?',
    faqA4: 'Standardní čas příjezdu je od 14:00, odjezd do 10:00. Při příjezdu vás osobně přivítáme, předáme vám klíče a zodpovíme veškeré dotazy. Pokud potřebujete jiný čas, dejte nám vědět předem!',
    faqQ5: 'Jak si mohu zarezervovat apartmán ve Scalee přímo?',
    faqA5: "Pošlete termín a počet hostů přes WhatsApp. Majitel ověří dostupnost, sdělí cenu a vysvětlí, jak rezervaci potvrdit.",
    faqQ6: 'Как проверить свободные даты?',
    faqA6: 'Вы можете просто написать нам в WhatsApp — мы быстро ответим, свободны ли апартаменты на ваши даты.',
    faqQ7: 'Je apartmán vhodný pro rodinnou dovolenou?',
    faqA7: "K dispozici je samostatná ložnice a kuchyň pro přípravu rodinných jídel. Napište počet dospělých a dětí a společně upřesníme místa na spaní i vaše přání.",
    guideTitle: 'Průvodce po Scalee',
    guideSubtitle: "Kam vyrazit během pobytu",
    guidePlace1: 'Restaurace "La Perla del Tirreno"',
    guideDesc1: "Tip na večeři s rybami a mořskými plody.",
    guidePlace2: 'Torre Talao',
    guideDesc2: "Jeden ze symbolů města Scalea, přibližně 12 minut pěšky od apartmánu.",
    guidePlace3: 'Staré město',
    guideDesc3: 'Úzké uličky, kde se zastavil čas. Ideální pro večerní procházku.',
    callUs: 'Zavolejte nám',
    priceFrom: 'od',
    meters: 'm',
    apt1Name: 'ScaleaStay',
    apt1Desc: "Apartmán s jednou ložnicí a vlastní terasou. Připravte si jídlo ve vybavené kuchyni, odpočiňte si po návratu z pláže a přijeďte na krátkou dovolenou i delší pobyt.",
    apt1Feature1: 'Klimatizace',
    apt1Feature2: 'Terasa',
    apt1Feature3: 'Parkování',
    rev1Name: 'Elena',
    rev1Text: 'Skvělé místo k pobytu. Čisté, útulné, nový nábytek a spotřebiče. Skvělá lokalita — jen kousek od promenády, obklopené obchody a restauracemi. Velmi spokojeni s naší volbou!',
    rev2Name: 'Mark',
    rev2Text: 'Čisté, útulné a velmi blízko pláže. Příští rok se určitě vrátíme.',
    rev3Name: 'Olga',
    rev3Text: 'Nejlepší lokalita ve Scalee. Staré město je pět minut chůze odtud.',
    directBookTitle: "Domluvte si pobyt přímo s majitelem",
    directBookItem1: "Proberte termín a svá přání přímo s majitelem",
    directBookItem2: "Zjistěte cenu a podmínky před rezervací",
    directBookItem3: "Zeptejte se na apartmán a příjezd přes WhatsApp",
    directBookItem4: 'Ověřené ubytování (jsme na Booking a Airbnb)',
    directBookItem5: 'Rychlé potvrzení po ověření dostupnosti',
    heroCtaHint: 'Napište nám na WhatsApp a ověřte dostupnost',
  }
};

export const SYSTEM_INSTRUCTION = `Вы — профессиональный виртуальный консьерж апартаментов "ScaleaStay" в Скалее, Италия. Ваша цель: помогать гостям спланировать идеальный отдых.

ФАКТЫ ОБ АПАРТАМЕНТАХ:
- Локация: Scalea, Calabria, Italy. Центральная часть города.
- Адрес: Via Giuseppe Saragat 11, Scalea.
- До ближайшего пляжа: примерно 600 м, обычно около 5–8 минут пешком.
- Супермаркет Interspar: примерно 230 м, около 3 минут пешком.
- Железнодорожная станция Scalea–Santa Domenica Talao: примерно 500 м, около 8 минут пешком.
- Удобства: парковка, кондиционер, терраса, оборудованная кухня, Wi‑Fi и газовое отопление.
- Владелец подтвердил установку интернета 18.09.2026. Не обещай конкретную скорость Wi‑Fi или пригодность для видеозвонков без замеров.
- Площадь внутри около 40 м²; терраса в эту площадь не входит.
- Длительное проживание в несезон — по запросу. Даты, срок и условия коммунальных платежей согласует владелец.
- Не называй цены, не обещай доступность или экономию на отоплении.

БРОНИРОВАНИЕ И НАЛИЧИЕ МЕСТ:
- Вы ИИ-консьерж, поэтому не видите календарь и не можете проверить свободные даты в реальном времени.
- Если гость спрашивает про свободные даты, цену, бронирование, как забронировать, можно ли приехать, семейный отдых или контакт с владельцем:
  Вы ОБЯЗАНЫ мягко ответить, что не видите календарь в реальном времени, и дать ПРЯМУЮ ССЫЛКУ на WhatsApp владельцу:
  https://wa.me/420774620060
- Не обещайте "мгновенное подтверждение" или "лучшую цену".

СТИЛЬ ОБЩЕНИЯ:
- Теплый, гостеприимный.
- Краткие, но информативные ответы.
- Отвечайте на том языке, на котором спрашивает гость.`;
