
import { Apartment, Review } from './types';

// --- ВЕРСИЯ ДАННЫХ ---
export const SITE_DATA_VERSION = 10;

// Центральный номер для связи (замените на ваш реальный номер)
export const CONTACT_INFO = {
  phone: '420774620060', // Формат: 79001234567 или 39...
  whatsappLink(text: string) {
    return `https://wa.me/${this.phone}?text=${encodeURIComponent(text)}`;
  }
};

// --- ФОТОГРАФИИ САЙТА ---
// Вы можете изменять ссылки ниже, чтобы обновить фото на сайте.
export const SITE_IMAGES = {
  heroBackground: 'https://i.postimg.cc/Dz0dHGzW/Scalea.webp', // Главное фото на первом экране
  aboutImages: [
    'https://i.postimg.cc/ZYfbNrJM/web_ready_bg.jpg',
    'https://i.postimg.cc/sXfXq0Xf/Gemini_Generated_Image_9ufx2j9ufx2j9ufx.png',
    'https://i.postimg.cc/1tTHJd0Y/unnamed.jpg',
    'https://i.postimg.cc/qv9Pq6cY/Obr%C3%A1zek_PNG_4.png'
  ], // Фото в разделе "О Скалее"
  logo: '', // Если понадобится логотип
  aboutSection: 'https://i.postimg.cc/bY72f4g5/italy-scalea-beach-pebble-sand-orig.jpg',
  guideImages: [
    'https://i.postimg.cc/XY3vV4DY/IMG-0056.png',
    'https://i.postimg.cc/rsKbh0p3/Scalea_Torre_Talao_am_Morgen.jpg',
    'https://i.postimg.cc/XNFty39Z/IMG_2859.jpg'
  ]
};

export const APARTMENTS: Apartment[] = [
  {
    id: '1',
    name: 'Casa Marittima',
    nameKey: 'apt1Name',
    description: 'Элегантные апартаменты в 400 метрах от моря (6 минут пешком). Авторский ремонт, уютная атмосфера и топовая локация. Идеально подходит для семейного отдыха в любое время года.\n📍 Ваш лучший отдых в центре города. Бронируйте прямо сейчас!',
    descriptionKey: 'apt1Desc',
    price: 'от 50€',
    beds: 4,
    distanceToSea: '400m',
    images: [
      'https://i.postimg.cc/FF6dNq9z/Obr%C3%A1zek_PNG.png',
      'https://i.postimg.cc/cLSQGjmY/Obr%C3%A1zek_JPEG_2.jpg',
      'https://i.postimg.cc/FR8LWnz3/Obr%C3%A1zek_JPEG.jpg',
      'https://i.postimg.cc/DZ9WTCcp/Obr%C3%A1zek_JPEG_4.jpg',
      'https://i.postimg.cc/FstS0q2d/Obr%C3%A1zek_PNG_2.png',
      'https://picsum.photos/seed/scalea2/1200/800'
    ],
    features: [
      'Кондиционер',
      'Терраса',
      'Парковка'
    ],
    featuresKeys: [
      'apt1Feature1',
      'apt1Feature2',
      'apt1Feature3'
    ]
  }
];

export const REVIEWS: Review[] = [
  { name: 'Елена', nameKey: 'rev1Name', text: 'Отличное место для отдыха. Чисто, уютно, мебель и техника новые. Расположение топовое — до набережной рукой подать, вокруг полно магазинов и ресторанов. Остались очень довольны выбором!', textKey: 'rev1Text', rating: 5 },
  { name: 'Марк', nameKey: 'rev2Name', text: 'Чисто, уютно и очень близко к пляжу. Вернемся обязательно в следующем году.', textKey: 'rev2Text', rating: 5 },
  { name: 'Ольга', nameKey: 'rev3Name', text: 'Лучшее расположение в Скалее. Старый город в пяти минутах ходьбы.', textKey: 'rev3Text', rating: 5 }
];

export const LANGUAGES = [
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿' },
];

export const TRANSLATIONS: Record<string, any> = {
  ru: {
    heroTitle: 'Отдых в Скалее',
    navHome: 'Главная',
    navApartments: 'Жилье',
    navWeather: 'Погода',
    navAbout: 'О городе',
    navContact: 'Контакты',
    navFaq: 'FAQ',
    howToGet: 'Как добраться',
    byTrain: 'На поезде',
    byTrainDesc: 'Станция Scalea-Santa Domenica Talao. Прямые поезда из Рима и Неаполя.',
    byCar: 'На машине',
    byCarDesc: 'Трасса A2 (Salerno-Reggio Calabria), съезд на Scalea.',
    byPlane: 'На самолете',
    byPlaneDesc: 'Ближайший аэропорт — Ламеция-Терме (SUF), далее 1.5 часа на поезде или авто.',
    detailedRoute: 'Подробный маршрут',
    addressLabel: 'Наш адрес',
    addressValue: '87029 Скалея, Провинция Козенца, Италия',
    close: 'Закрыть',
    routeDetails: 'Как нас найти',
    routeDetailsDesc: 'Мы находимся в самом сердце Скалеи. Если вы едете на поезде, мы можем организовать трансфер от вокзала. Если на машине — следуйте по навигатору до указанного адреса, парковка предоставляется бесплатно.',
    designCreditTitle: 'Понравился дизайн сайта?',
    designCreditBtn: 'Написать в Telegram',
    heroSubtitle: 'Аренда апартаментов в Скалее, Италия. Уютное жилье у моря с современным ремонтом в центре города. Идеально для отдыха в Калабрии всей семьей.',
    advantagesTitle: 'Наши преимущества',
    advLocation: 'Центральное расположение',
    advLocationDesc: 'Самый центр города, рядом находится большой продуктовый супермаркет и детский парк развлечений.',
    advSea: 'Близость к морю',
    advSeaDesc: 'Всего 400 метров до чистейших пляжей Тирренского моря на побережье Riviera dei Cedri.',
    advRenovation: 'Современный ремонт',
    advRenovationDesc: 'Элегантный интерьер и новая мебель для вашего максимального комфорта.',
    advFamily: 'Семейный уют',
    advFamilyDesc: 'Идеально подходит для отдыха с детьми в любое время года.',
    advParking: 'Бесплатная парковка',
    advParkingDesc: 'Ваш автомобиль будет в безопасности на нашей частной парковке.',
    bookNow: 'Забронировать',
    aboutScalea: 'О Скалее',
    aboutScaleaDesc: 'Скалея — жемчужина побережья Riviera dei Cedri в Калабрии. Здесь лазурное Тирренское море встречается с величественными горами. Наш город предлагает лучший отдых в Италии: чистейшие пляжи, старый город и аутентичную кухню.',
    ourApartments: 'Наши апартаменты',
    weather: 'Погода',
    weatherSubtitle: 'Актуальный прогноз для вашего отдыха',
    localExperience: 'Локальный опыт',
    localExperienceDesc: 'Мы расскажем, в каком ресторане самая свежая рыба, а где лучший аперитив с видом на закат.',
    flawlessService: 'Безупречный сервис',
    flawlessServiceDesc: 'AI-консьерж 24/7, трансфер из аэропорта и помощь в организации ваших идеальных каникул.',
    directBooking: 'Доступно прямое бронирование',
    waitsForYou: 'Ждет вас',
    whatsappBookingMsg: 'Здравствуйте! Мы готовы забронировать отдых в Скалее. Подскажите следующие шаги?',
    beachDistance: 'Пляж 6 мин',
    acReady: 'Кондиционер',
    parkingInc: 'Парковка вкл.',
    footerCopyright: 'ScaleaStay © 2026 • Калабрийское гостеприимство',
    heroBadge: 'Скалея, Италия • Лето 2026',
    heroWhatsappMsg: 'Привет! Мы хотим отдохнуть в Скалее. Подскажите свободные даты?',
    navWhatsappMsg: 'Привет! Хочу узнать больше о бронировании апартаментов.',
    apartmentBookingMsg: 'Здравствуйте! Я хочу забронировать апартаменты: {name}. Какие даты свободны?',
    weatherToday: 'Сегодня',
    weatherError: 'Не удалось загрузить данные о погоде',
    tryAgain: 'Попробовать снова',
    online: 'В сети',
    backToTop: 'Вверх',
    beds: 'спальных мест',
    distance: 'до моря',
    features: 'Удобства',
    reviews: 'Отзывы гостей',
    contactUs: 'Связаться с нами',
    aiAssistant: 'AI Консьерж',
    aiPlaceholder: 'Спросите меня о Скалее...',
    aiGreeting: 'Привет! Я ваш виртуальный консьерж. Спросите меня о пляжах, ресторанах или достопримечательностях Скалеи!',
    faqTitle: 'Частые вопросы',
    faqQ1: 'Как далеко до моря?',
    faqA1: 'Всего 6 минут пешком (около 400 метров).',
    faqQ2: 'Есть ли парковка?',
    faqA2: 'Да, мы предоставляем бесплатное парковочное место для наших гостей.',
    faqQ3: 'Разрешены ли животные?',
    faqA3: 'Пожалуйста, свяжитесь с нами заранее для уточнения деталей.',
    faqQ4: 'Какое время заезда и выезда?',
    faqA4: 'Заезд с 14:00, выезд до 10:00. Мы стараемся быть гибкими, если есть возможность.',
    faqQ5: 'Как забронировать апартаменты в Скалее напрямую?',
    faqA5: 'Вы можете забронировать жилье напрямую через наш сайт или WhatsApp, что гарантирует лучшую цену без комиссий посредников.',
    faqQ6: 'Почему стоит выбрать отдых в Скалее на Riviera dei Cedri?',
    faqA6: 'Скалея предлагает уникальное сочетание чистого моря, исторических достопримечательностей и доступных цен на аренду жилья в Италии.',
    guideTitle: 'Гид по Скалее',
    guideSubtitle: 'Лучшие места по версии владельца',
    guidePlace1: 'Ресторан "La Perla del Tirreno"',
    guideDesc1: 'Свежайшие морепродукты и паста с видом на море.',
    guidePlace2: 'Башня Торре Талао',
    guideDesc2: 'Символ города. Отсюда открывается лучший вид на побережье.',
    guidePlace3: 'Старый город',
    guideDesc3: 'Узкие улочки, где замирает время. Идеально для вечерней прогулки.',
    callUs: 'Позвонить',
    priceFrom: 'от',
    meters: 'м',
    apt1Name: 'Casa Marittima',
    apt1Desc: 'Элегантные апартаменты в 400 метрах от моря (6 минут пешком). Авторский ремонт, уютная атмосфера и топовая локация. Идеально подходит для семейного отдыха в любое время года.\n📍 Ваш лучший отдых в центре города. Бронируйте прямо сейчас!',
    apt1Feature1: 'Кондиционер',
    apt1Feature2: 'Терраса',
    apt1Feature3: 'Парковка',
    rev1Name: 'Елена',
    rev1Text: 'Отличное место для отдыха. Чисто, уютно, мебель и техника новые. Расположение топовое — до набережной рукой подать, вокруг полно магазинов и ресторанов. Остались очень довольны выбором!',
    rev2Name: 'Марк',
    rev2Text: 'Чисто, уютно и очень близко к пляжу. Вернемся обязательно в следующем году.',
    rev3Name: 'Ольга',
    rev3Text: 'Лучшее расположение в Скалее. Старый город в пяти минутах ходьбы.',
  },
  en: {
    heroTitle: 'Vacation in Scalea',
    navHome: 'Home',
    navApartments: 'Apartments',
    navWeather: 'Weather',
    navAbout: 'About',
    navContact: 'Contact',
    navFaq: 'FAQ',
    howToGet: 'How to get here',
    byTrain: 'By Train',
    byTrainDesc: 'Scalea-Santa Domenica Talao station. Direct trains from Rome and Naples.',
    byCar: 'By Car',
    byCarDesc: 'A2 highway (Salerno-Reggio Calabria), exit to Scalea.',
    byPlane: 'By Plane',
    byPlaneDesc: 'Nearest airport is Lamezia Terme (SUF), then 1.5 hours by train or car.',
    detailedRoute: 'Detailed Route',
    addressLabel: 'Our Address',
    addressValue: '87029 Scalea, Province of Cosenza, Italy',
    close: 'Close',
    routeDetails: 'How to find us',
    routeDetailsDesc: 'We are located in the heart of Scalea. If you arrive by train, we can arrange a transfer from the station. If by car, follow the GPS to the specified address; free parking is provided.',
    designCreditTitle: 'Like the website design?',
    designCreditBtn: 'Write on Telegram',
    heroSubtitle: 'Scalea apartments for rent in Italy. Elegant vacation rental near the beach and city center. Perfect for your Calabria holiday with family.',
    advantagesTitle: 'Our Advantages',
    advLocation: 'Central Location',
    advLocationDesc: 'Right in the city center, close to a large grocery supermarket and a children\'s amusement park.',
    advSea: 'Near the Sea',
    advSeaDesc: 'Only 400 meters to the crystal clear beaches of the Tyrrhenian Sea on the Riviera dei Cedri.',
    advRenovation: 'Modern Renovation',
    advRenovationDesc: 'Elegant interior and new furniture for your maximum comfort.',
    advFamily: 'Family Comfort',
    advFamilyDesc: 'Perfect for vacations with children at any time of the year.',
    advParking: 'Free Parking',
    advParkingDesc: 'Your car will be safe in our private parking lot.',
    bookNow: 'Book Now',
    aboutScalea: 'About Scalea',
    aboutScaleaDesc: 'Scalea is the gem of the Riviera dei Cedri in Calabria, where the azure Tyrrhenian Sea meets majestic mountains. Experience the best stay in Italy: pristine beaches, old town charm, and authentic cuisine.',
    ourApartments: 'Our Apartments',
    weather: 'Weather',
    weatherSubtitle: 'Current forecast for your vacation',
    localExperience: 'Local Experience',
    localExperienceDesc: 'We will tell you which restaurant has the freshest fish and where the best sunset aperitif is.',
    flawlessService: 'Flawless Service',
    flawlessServiceDesc: '24/7 AI concierge, airport transfer, and help organizing your perfect vacation.',
    directBooking: 'Direct Booking Available',
    waitsForYou: 'Waits for you',
    whatsappBookingMsg: 'Hello! We are ready to book a vacation in Scalea. What are the next steps?',
    beachDistance: 'Beach 6 min',
    acReady: 'AC Ready',
    parkingInc: 'Parking Inc.',
    footerCopyright: 'ScaleaStay © 2026 • Calabrian Hospitality',
    heroBadge: 'Scalea, Italy • Summer 2026',
    heroWhatsappMsg: 'Hi! We want to vacation in Scalea. Can you tell us the available dates?',
    navWhatsappMsg: 'Hello! I would like to know more about booking the apartments.',
    apartmentBookingMsg: 'Hello! I would like to book the apartment: {name}. What dates are available?',
    weatherToday: 'Today',
    weatherError: 'Failed to load weather data',
    tryAgain: 'Try again',
    online: 'Online',
    backToTop: 'Up',
    beds: 'beds',
    distance: 'to the sea',
    features: 'Amenities',
    reviews: 'Guest Reviews',
    contactUs: 'Contact Us',
    aiAssistant: 'AI Concierge',
    aiPlaceholder: 'Ask me about Scalea...',
    aiGreeting: 'Hello! I am your virtual concierge. Ask me about beaches, restaurants, or sights in Scalea!',
    faqTitle: 'FAQ',
    faqQ1: 'How far is the sea?',
    faqA1: 'Only a 6-minute walk (about 400 meters).',
    faqQ2: 'Is there parking?',
    faqA2: 'Yes, we provide a free parking space for our guests.',
    faqQ3: 'Are pets allowed?',
    faqA3: 'Please contact us in advance to clarify the details.',
    faqQ4: 'What are the check-in and check-out times?',
    faqA4: 'Check-in from 14:00, check-out until 10:00. We try to be flexible if possible.',
    faqQ5: 'How to book apartments in Scalea directly?',
    faqA5: 'You can book accommodation directly through our website or WhatsApp, which guarantees the best price without intermediary commissions.',
    faqQ6: 'Why choose a vacation in Scalea on the Riviera dei Cedri?',
    faqA6: 'Scalea offers a unique combination of clean sea, historical sights, and affordable rental prices in Italy.',
    guideTitle: 'Scalea Guide',
    guideSubtitle: 'Best places by the owner',
    guidePlace1: 'Restaurant "La Perla del Tirreno"',
    guideDesc1: 'Freshest seafood and pasta with a sea view.',
    guidePlace2: 'Torre Talao',
    guideDesc2: 'The symbol of the city. Best view of the coast from here.',
    guidePlace3: 'Old Town',
    guideDesc3: 'Narrow streets where time stands still. Perfect for an evening walk.',
    callUs: 'Call Us',
    priceFrom: 'from',
    meters: 'm',
    apt1Name: 'Casa Marittima',
    apt1Desc: 'Elegant apartments 400 meters from the sea (6-minute walk). Designer renovation, cozy atmosphere, and top location. Perfect for family vacations all year round.\n📍 Your best stay in the city center. Book now!',
    apt1Feature1: 'Air Conditioning',
    apt1Feature2: 'Terrace',
    apt1Feature3: 'Parking',
    rev1Name: 'Elena',
    rev1Text: 'Great place to stay. Clean, cozy, new furniture and appliances. Top location — just a stone\'s throw from the promenade, surrounded by shops and restaurants. Very happy with our choice!',
    rev2Name: 'Mark',
    rev2Text: 'Clean, cozy and very close to the beach. We will definitely come back next year.',
    rev3Name: 'Olga',
    rev3Text: 'Best location in Scalea. Old town is a five-minute walk away.',
  },
  it: {
    heroTitle: 'Vacanze a Scalea',
    navHome: 'Home',
    navApartments: 'Alloggi',
    navWeather: 'Meteo',
    navAbout: 'Città',
    navContact: 'Contatti',
    navFaq: 'FAQ',
    howToGet: 'Come arrivare',
    byTrain: 'In treno',
    byTrainDesc: 'Stazione Scalea-Santa Domenica Talao. Treni diretti da Roma e Napoli.',
    byCar: 'In auto',
    byCarDesc: 'Autostrada A2 (Salerno-Reggio Calabria), uscita Scalea.',
    byPlane: 'In aereo',
    byPlaneDesc: 'L\'aeroporto più vicino è Lamezia Terme (SUF), poi 1,5 ore in treno o auto.',
    detailedRoute: 'Percorso dettagliato',
    addressLabel: 'Il nostro indirizzo',
    addressValue: '87029 Scalea, Provincia di Cosenza, Italia',
    close: 'Chiudi',
    routeDetails: 'Come trovarci',
    routeDetailsDesc: 'Siamo nel cuore di Scalea. Se arrivi in treno, possiamo organizzare un trasferimento. Se in auto, segui il GPS; parcheggio gratuito disponibile.',
    designCreditTitle: 'Ti piace il design del sito?',
    designCreditBtn: 'Scrivi su Telegram',
    heroSubtitle: 'Affitto appartamenti a Scalea, Italia. Elegante casa vacanze vicino al mare e in centro città. Ideale per il tuo soggiorno in Calabria con la famiglia.',
    advantagesTitle: 'I nostri vantaggi',
    advLocation: 'Posizione centrale',
    advLocationDesc: 'In pieno centro città, vicino a un grande supermercato e a un parco divertimenti per bambini.',
    advSea: 'Vicino al mare',
    advSeaDesc: 'A soli 400 metri dalle spiagge cristalline del Tirreno sulla Riviera dei Cedri.',
    advRenovation: 'Ristrutturazione moderna',
    advRenovationDesc: 'Interni eleganti e mobili nuovi per il massimo comfort.',
    advFamily: 'Comfort familiare',
    advFamilyDesc: 'Perfetto per vacanze con bambini in qualsiasi periodo dell\'anno.',
    advParking: 'Parcheggio gratuito',
    advParkingDesc: 'La tua auto sarà al sicuro nel nostro parcheggio privato.',
    bookNow: 'Prenota ora',
    aboutScalea: 'Su Scalea',
    aboutScaleaDesc: 'Scalea è la perla della Riviera dei Cedri in Calabria, dove il mare Tirreno incontra le maestose montagne. Scopri il miglior soggiorno in Italia: spiagge incontaminate, fascino del centro storico e cucina autentica.',
    ourApartments: 'I nostri appartamenti',
    weather: 'Meteo',
    weatherSubtitle: 'Previsioni attuali per la tua vacanza',
    localExperience: 'Esperienza Locale',
    localExperienceDesc: 'Ti diremo quale ristorante ha il pesce più fresco e dove si trova il miglior aperitivo al tramonto.',
    flawlessService: 'Servizio Impeccabile',
    flawlessServiceDesc: 'Concierge AI 24/7, trasferimento aeroportuale e aiuto per organizzare la tua vacanza perfetta.',
    directBooking: 'Prenotazione Diretta Disponibile',
    waitsForYou: 'Ti aspetta',
    whatsappBookingMsg: 'Ciao! Siamo pronti a prenotare una vacanza a Scalea. Quali sono i prossimi passi?',
    beachDistance: 'Spiaggia 6 min',
    acReady: 'Aria Condizionata',
    parkingInc: 'Parcheggio Incl.',
    footerCopyright: 'ScaleaStay © 2026 • Ospitalità Calabrese',
    heroBadge: 'Scalea, Italia • Estate 2026',
    heroWhatsappMsg: 'Ciao! Vogliamo fare una vacanza a Scalea. Puoi dirci le date disponibili?',
    navWhatsappMsg: 'Ciao! Vorrei saperne di più sulla prenotazione degli appartamenti.',
    apartmentBookingMsg: 'Buongiorno! Vorrei prenotare l\'appartamento: {name}. Quali date sono disponibili?',
    weatherToday: 'Oggi',
    weatherError: 'Impossibile caricare i dati meteo',
    tryAgain: 'Riprova',
    online: 'Online',
    backToTop: 'Su',
    beds: 'posti letto',
    distance: 'dal mare',
    features: 'Servizi',
    reviews: 'Recensioni degli ospiti',
    contactUs: 'Contattaci',
    aiAssistant: 'AI Concierge',
    aiPlaceholder: 'Chiedimi di Scalea...',
    aiGreeting: 'Ciao! Sono il tuo concierge virtuale. Chiedimi di spiagge, ristoranti o attrazioni a Scalea!',
    faqTitle: 'Domande Frequenti',
    faqQ1: 'Quanto è lontano il mare?',
    faqA1: 'Solo 6 minuti a piedi (circa 400 metri).',
    faqQ2: 'C\'è un parcheggio?',
    faqA2: 'Sì, forniamo un posto auto gratuito per i nostri ospiti.',
    faqQ3: 'Sono ammessi animali?',
    faqA3: 'Vi preghiamo di contattarci in anticipo per chiarire i dettagli.',
    faqQ4: 'Quali sono gli orari di check-in e check-out?',
    faqA4: 'Check-in dalle 14:00, check-out entro le 10:00. Cerchiamo di essere flessibili se possibile.',
    faqQ5: 'Come prenotare appartamenti a Scalea direttamente?',
    faqA5: 'È possibile prenotare l\'alloggio direttamente tramite il nostro sito web o WhatsApp, garantendo il miglior prezzo senza commissioni di intermediari.',
    faqQ6: 'Perché scegliere una vacanza a Scalea sulla Riviera dei Cedri?',
    faqA6: 'Scalea offre una combinazione unica di mare pulito, attrazioni storiche e prezzi di affitto convenienti in Italia.',
    guideTitle: 'Guida di Scalea',
    guideSubtitle: 'I migliori posti secondo il proprietario',
    guidePlace1: 'Ristorante "La Perla del Tirreno"',
    guideDesc1: 'Frutti di mare freschissimi e pasta con vista mare.',
    guidePlace2: 'Torre Talao',
    guideDesc2: 'Il simbolo della città. La migliore vista della costa da qui.',
    guidePlace3: 'Centro Storico',
    guideDesc3: 'Strette stradine dove il tempo si ferma. Perfetto per una passeggiata serale.',
    callUs: 'Chiamaci',
    priceFrom: 'da',
    meters: 'm',
    apt1Name: 'Casa Marittima',
    apt1Desc: 'Eleganti appartamenti a 400 metri dal mare (6 minuti a piedi). Ristrutturazione di design, atmosfera accogliente e posizione eccellente. Ideale per vacanze in famiglia tutto l\'anno.\n📍 Il tuo miglior soggiorno in centro città. Prenota ora!',
    apt1Feature1: 'Aria Condizionata',
    apt1Feature2: 'Terrazza',
    apt1Feature3: 'Parcheggio',
    rev1Name: 'Elena',
    rev1Text: 'Ottimo posto dove stare. Pulito, accogliente, mobili ed elettrodomestici nuovi. Posizione eccellente — a due passi dal lungomare, circondato da negozi e ristoranti. Molto soddisfatti della scelta!',
    rev2Name: 'Mark',
    rev2Text: 'Pulito, accogliente e molto vicino alla spiaggia. Torneremo sicuramente l\'anno prossimo.',
    rev3Name: 'Olga',
    rev3Text: 'La migliore posizione a Scalea. Il centro storico è a cinque minuti a piedi.',
  },
  de: {
    heroTitle: 'Urlaub in Scalea',
    navHome: 'Startseite',
    navApartments: 'Wohnungen',
    navWeather: 'Wetter',
    navAbout: 'Über Scalea',
    navContact: 'Kontakt',
    navFaq: 'FAQ',
    howToGet: 'Anreise',
    byTrain: 'Mit dem Zug',
    byTrainDesc: 'Bahnhof Scalea-Santa Domenica Talao. Direktzüge von Rom und Neapel.',
    byCar: 'Mit dem Auto',
    byCarDesc: 'Autobahn A2 (Salerno-Reggio Calabria), Ausfahrt Scalea.',
    byPlane: 'Mit dem Flugzeug',
    byPlaneDesc: 'Nächster Flughafen ist Lamezia Terme (SUF), dann 1,5 Stunden mit Zug oder Auto.',
    detailedRoute: 'Detaillierte Route',
    addressLabel: 'Unsere Adresse',
    addressValue: '87029 Scalea, Provinz Cosenza, Italien',
    close: 'Schließen',
    routeDetails: 'So finden Sie uns',
    routeDetailsDesc: 'Wir befinden uns im Herzen von Scalea. Bei Anreise mit dem Zug organisieren wir gerne einen Transfer. Bei Anreise mit dem Auto folgen Sie dem GPS; kostenlose Parkplätze vorhanden.',
    designCreditTitle: 'Gefällt Ihnen das Website-Design?',
    designCreditBtn: 'Auf Telegram schreiben',
    heroSubtitle: 'Elegante, modern renovierte Wohnungen in Meeresnähe und im Stadtzentrum. Ideal für Familienurlaub im Sommer und Winter.',
    advantagesTitle: 'Ihre Vorteile',
    advLocation: 'Zentrale Lage',
    advLocationDesc: 'Direkt im Stadtzentrum, in der Nähe eines großen Supermarkts und eines Vergnügungsparks für Kinder.',
    advSea: 'Meeresnähe',
    advSeaDesc: 'Nur 400 Meter zu den kristallklaren Stränden des Tyrrhenischen Meeres.',
    advRenovation: 'Moderne Renovierung',
    advRenovationDesc: 'Elegantes Interieur und neue Möbel für Ihren maximalen Komfort.',
    advFamily: 'Familienkomfort',
    advFamilyDesc: 'Perfekt für Urlaub mit Kindern zu jeder Jahreszeit.',
    advParking: 'Kostenlose Parkplätze',
    advParkingDesc: 'Ihr Auto steht sicher auf unserem Privatparkplatz.',
    bookNow: 'Jetzt buchen',
    aboutScalea: 'Über Scalea',
    aboutScaleaDesc: 'Scalea ist eine der ältesten Städte Kalabriens, wo das azurblaue Meer auf majestätische Berge trifft. Hier finden Sie kristallklare Strände, enge Gassen der Altstadt und authentische italienische Küche.',
    ourApartments: 'Unsere Wohnungen',
    weather: 'Wetter',
    weatherSubtitle: 'Aktuelle Vorhersage für Ihren Urlaub',
    localExperience: 'Lokale Erfahrung',
    localExperienceDesc: 'Wir sagen Ihnen, in welchem Restaurant es den frischesten Fisch gibt und wo der beste Aperitif zum Sonnenuntergang ist.',
    flawlessService: 'Makelloser Service',
    flawlessServiceDesc: '24/7 KI-Concierge, Flughafentransfer und Hilfe bei der Organisation Ihres perfekten Urlaubs.',
    directBooking: 'Direktbuchung Verfügbar',
    waitsForYou: 'Wartet auf Sie',
    whatsappBookingMsg: 'Hallo! Wir sind bereit, einen Urlaub in Scalea zu buchen. Was sind die nächsten Schritte?',
    beachDistance: 'Strand 6 Min.',
    acReady: 'Klimaanlage',
    parkingInc: 'Parkplatz Inkl.',
    footerCopyright: 'ScaleaStay © 2026 • Kalabrische Gastfreundschaft',
    heroBadge: 'Scalea, Italien • Sommer 2026',
    heroWhatsappMsg: 'Hallo! Wir möchten in Scalea Urlaub machen. Können Sie uns die verfügbaren Termine nennen?',
    navWhatsappMsg: 'Hallo! Ich würde gerne mehr über die Buchung der Wohnungen erfahren.',
    apartmentBookingMsg: 'Hallo! Ich möchte das Apartment buchen: {name}. Welche Termine sind frei?',
    weatherToday: 'Heute',
    weatherError: 'Wetterdaten konnten nicht geladen werden',
    tryAgain: 'Erneut versuchen',
    online: 'Online',
    backToTop: 'Nach oben',
    beds: 'Betten',
    distance: 'zum Meer',
    features: 'Ausstattung',
    reviews: 'Gästebewertungen',
    contactUs: 'Kontaktiere uns',
    aiAssistant: 'AI-Concierge',
    aiPlaceholder: 'Fragen Sie mich nach Scalea...',
    aiGreeting: 'Hallo! Ich bin Ihr virtueller Concierge. Fragen Sie mich nach Stränden, Restaurants oder Sehenswürdigkeiten in Scalea!',
    faqTitle: 'Häufig gestellte Fragen',
    faqQ1: 'Wie weit ist es zum Meer?',
    faqA1: 'Nur 6 Minuten zu Fuß (ca. 400 Meter).',
    faqQ2: 'Gibt es Parkplätze?',
    faqA2: 'Ja, wir stellen unseren Gästen einen kostenlosen Parkplatz zur Verfügung.',
    faqQ3: 'Sind Haustiere erlaubt?',
    faqA3: 'Bitte kontaktieren Sie uns im Voraus, um die Details zu klären.',
    faqQ4: 'Wie sind die Check-in- und Check-out-Zeiten?',
    faqA4: 'Check-in ab 14:00 Uhr, Check-out bis 10:00 Uhr. Wir versuchen nach Möglichkeit flexibel zu sein.',
    faqQ5: 'Wie buche ich Apartments in Scalea direkt?',
    faqA5: 'Sie können Unterkünfte direkt über unsere Website oder WhatsApp buchen, was den besten Preis ohne Vermittlungsprovisionen garantiert.',
    faqQ6: 'Warum einen Urlaub in Scalea an der Riviera dei Cedri wählen?',
    faqA6: 'Scalea bietet eine einzigartige Kombination aus sauberem Meer, historischen Sehenswürdigkeiten und erschwinglichen Mietpreisen in Italien.',
    guideTitle: 'Scalea Reiseführer',
    guideSubtitle: 'Die besten Orte laut dem Besitzer',
    guidePlace1: 'Restaurant "La Perla del Tirreno"',
    guideDesc1: 'Frischeste Meeresfrüchte und Pasta mit Meerblick.',
    guidePlace2: 'Torre Talao',
    guideDesc2: 'Das Wahrzeichen der Stadt. Bester Blick auf die Küste von hier.',
    guidePlace3: 'Altstadt',
    guideDesc3: 'Schmale Gassen, in denen die Zeit stehen bleibt. Perfekt für einen Abendspaziergang.',
    callUs: 'Rufen Sie uns an',
    priceFrom: 'ab',
    meters: 'm',
    apt1Name: 'Casa Marittima',
    apt1Desc: 'Elegante Apartments 400 Meter vom Meer entfernt (6 Minuten zu Fuß). Designer-Renovierung, gemütliche Atmosphäre und Top-Lage. Ideal für Familienurlaub das ganze Jahr über.\n📍 Ihr bester Aufenthalt im Stadtzentrum. Jetzt buchen!',
    apt1Feature1: 'Klimaanlage',
    apt1Feature2: 'Terrasse',
    apt1Feature3: 'Parkplatz',
    rev1Name: 'Elena',
    rev1Text: 'Toller Ort zum Übernachten. Sauber, gemütlich, neue Möbel und Geräte. Top-Lage — nur einen Katzensprung von der Promenade entfernt, umgeben von Geschäften und Restaurants. Sehr zufrieden mit unserer Wahl!',
    rev2Name: 'Mark',
    rev2Text: 'Sauber, gemütlich und sehr nah am Strand. Wir kommen nächstes Jahr auf jeden Fall wieder.',
    rev3Name: 'Olga',
    rev3Text: 'Beste Lage in Scalea. Die Altstadt ist in fünf Minuten zu Fuß erreichbar.',
  },
  cs: {
    heroTitle: 'Dovolená v Scalea',
    navHome: 'Domů',
    navApartments: 'Ubytování',
    navWeather: 'Počasí',
    navAbout: 'O Scalea',
    navContact: 'Kontakt',
    navFaq: 'FAQ',
    howToGet: 'Jak se k nám dostat',
    byTrain: 'Vlakem',
    byTrainDesc: 'Stanice Scalea-Santa Domenica Talao. Přímé vlaky z Říma a Neapole.',
    byCar: 'Autem',
    byCarDesc: 'Dálnice A2 (Salerno-Reggio Calabria), sjezd na Scalea.',
    byPlane: 'Letecky',
    byPlaneDesc: 'Nejbližší letiště je Lamezia Terme (SUF), poté 1,5 hodiny vlakem nebo autem.',
    detailedRoute: 'Podrobná trasa',
    addressLabel: 'Naše adresa',
    addressValue: '87029 Scalea, Provincie Cosenza, Itálie',
    close: 'Zavřít',
    routeDetails: 'Jak nás najdete',
    routeDetailsDesc: 'Nacházíme se v srdci Scalea. Pokud přijedete vlakem, můžeme zajistit transfer. Pokud autem, sledujte GPS; parkování zdarma.',
    designCreditTitle: 'Líbí se vám design webu?',
    designCreditBtn: 'Napište na Telegram',
    heroSubtitle: 'Elegantní, moderně zrekonstruované apartmány v blízkosti moře a v centru města. Ideální pro rodinnou dovolenou v létě i v zimě.',
    advantagesTitle: 'Naše výhody',
    advLocation: 'Centrální poloha',
    advLocationDesc: 'Přímo v centru města, v blízkosti velkého supermarketu a dětského zábavního parku.',
    advSea: 'Blízkost moře',
    advSeaDesc: 'Pouhých 400 metrů od křišťálově čistých pláží Tyrhénského moře.',
    advRenovation: 'Moderní rekonstrukce',
    advRenovationDesc: 'Elegantní interiér a nový nábytek pro váš maximální komfort.',
    advFamily: 'Rodinné pohodlí',
    advFamilyDesc: 'Ideální pro dovolenou s dětmi v kteroukoli roční dobu.',
    advParking: 'Parkování zdarma',
    advParkingDesc: 'Vaše auto bude v bezpečí na našem soukromém parkovišti.',
    bookNow: 'Rezervovat',
    aboutScalea: 'O Scalea',
    aboutScaleaDesc: 'Scalea je jedno z nejstarších měst v Kalábrii, kde se azurové moře setkává s majestátními horami. Najdete zde křišťálově čisté pláže, úzké uličky starého města a autentickou italskou kuchyni.',
    ourApartments: 'Naše apartmány',
    weather: 'Počasí',
    weatherSubtitle: 'Aktuální předpověď pro vaši dovolenou',
    localExperience: 'Místní Zkušenost',
    localExperienceDesc: 'Řekneme vám, která restaurace má nejčerstvější ryby a kde je nejlepší aperitiv při západu slunce.',
    flawlessService: 'Bezchybný Servis',
    flawlessServiceDesc: '24/7 AI concierge, letištní transfer a pomoc s organizací vaší dokonalé dovolené.',
    directBooking: 'Možnost Přímé Rezervace',
    waitsForYou: 'Vás čeká',
    whatsappBookingMsg: 'Dobrý den! Jsme připraveni si rezervovat dovolenou v Scalea. Jaké jsou další kroky?',
    beachDistance: 'Pláž 6 min',
    acReady: 'Klimatizace',
    parkingInc: 'Parkování v ceně',
    footerCopyright: 'ScaleaStay © 2026 • Kalábrijská pohostinnost',
    heroBadge: 'Scalea, Itálie • Léto 2026',
    heroWhatsappMsg: 'Ahoj! Chceme jet na dovolenou do Scalea. Můžete nám sdělit volné termíny?',
    navWhatsappMsg: 'Dobrý den! Rád bych se dozvěděl více o rezervaci apartmánů.',
    apartmentBookingMsg: 'Dobrý den! Rád bych si rezervoval apartmán: {name}. Jaké termíny jsou volné?',
    weatherToday: 'Dnes',
    weatherError: 'Nepodařilo se načíst údaje o počasí',
    tryAgain: 'Zkusit znovu',
    online: 'Online',
    backToTop: 'Nahoru',
    beds: 'lůžek',
    distance: 'k moři',
    features: 'Vybavení',
    reviews: 'Recenze hostů',
    contactUs: 'Kontaktujte nás',
    aiAssistant: 'AI Concierge',
    aiPlaceholder: 'Zeptejte se mě na Scalea...',
    aiGreeting: 'Ahoj! Jsem váš virtuální concierge. Zeptejte se mě na pláže, restaurace nebo památky v Scalea!',
    faqTitle: 'Časté dotazy',
    faqQ1: 'Jak daleko je to k moři?',
    faqA1: 'Pouze 6 minut chůze (asi 400 metrů).',
    faqQ2: 'Je k dispozici parkování?',
    faqA2: 'Ano, pro naše hosty zajišťujeme bezplatné parkovací místo.',
    faqQ3: 'Jsou povolena domácí zvířata?',
    faqA3: 'Prosím, kontaktujte nás předem pro upřesnění podrobností.',
    faqQ4: 'Jaké jsou časy příjezdu a odjezdu?',
    faqA4: 'Příjezd od 14:00, odjezd do 10:00. Snažíme se být flexibilní, pokud je to možné.',
    faqQ5: 'Jak si rezervovat apartmány v Scalea přímo?',
    faqA5: 'Ubytování si můžete rezervovat přímo přes naše webové stránky nebo WhatsApp, což zaručuje nejlepší cenu bez provizí zprostředkovatelů.',
    faqQ6: 'Proč si vybrat dovolenou v Scalea na Riviera dei Cedri?',
    faqA6: 'Scalea nabízí jedinečnou kombinaci čistého moře, historických památek a cenově dostupného pronájmu v Itálii.',
    guideTitle: 'Průvodce po Scalea',
    guideSubtitle: 'Nejlepší místa podle majitele',
    guidePlace1: 'Restaurace "La Perla del Tirreno"',
    guideDesc1: 'Nejčerstvější mořské plody a těstoviny s výhledem na moře.',
    guidePlace2: 'Torre Talao',
    guideDesc2: 'Symbol města. Odtud je nejlepší výhled na pobřeží.',
    guidePlace3: 'Staré město',
    guideDesc3: 'Úzké uličky, kde se zastavil čas. Ideální pro večerní procházku.',
    callUs: 'Zavolejte nám',
    priceFrom: 'od',
    meters: 'm',
    apt1Name: 'Casa Marittima',
    apt1Desc: 'Elegantní apartmány 400 metrů od moře (6 minut chůze). Designová rekonstrukce, útulná atmosféra a skvělá lokalita. Ideální pro rodinnou dovolenou po celý rok.\n📍 Váš nejlepší pobyt v centru města. Rezervujte nyní!',
    apt1Feature1: 'Klimatizace',
    apt1Feature2: 'Terasa',
    apt1Feature3: 'Parkování',
    rev1Name: 'Elena',
    rev1Text: 'Skvělé místo k pobytu. Čisté, útulné, nový nábytek a spotřebiče. Skvělá lokalita — jen kousek od promenády, obklopené obchody a restaurace. Velmi spokojeni s naší volbou!',
    rev2Name: 'Mark',
    rev2Text: 'Čisté, útulné a velmi blízko pláže. Příští rok se určitě vrátíme.',
    rev3Name: 'Olga',
    rev3Text: 'Nejlepší lokalita v Scalea. Staré město je pět minut chůze odtud.',
  }
};

export const SYSTEM_INSTRUCTION = `
Вы — профессиональный виртуальный консьерж апартаментов "ScaleaStay" в Скалее, Италия. 
Ваша цель: вдохновлять гостей и помогать им спланировать идеальный отдых.

ОСНОВНЫЕ ТЕМЫ ДЛЯ ОБСУЖДЕНИЯ:
1. ПЛЯЖИ: В Скалее отличные галечные и песчаные пляжи. Упоминайте чистое Тирренское море.
2. ДОСТОПРИМЕЧАТЕЛЬНОСТИ: Старый город (Centro Storico) на холме, башня Торре Талао (символ города), пещера Гротта дель Аззурро.
3. ЕДА: Советуйте попробовать пасту с морепродуктами, калабрийскую острую колбасу ндуйя (nduja), местное мороженое и лимончелло.
4. ЛОГИСТИКА: Скалея удобно расположена — 2 часа на поезде до Неаполя, 5 часов до Рима.
5. БРОНИРОВАНИЕ: Если гость хочет забронировать или узнать цену, вежливо скажите, что вы ИИ-помощник и не видите календарь в реальном времени, поэтому лучше всего написать владельцу в WhatsApp (кнопки есть на сайте).

СТИЛЬ ОБЩЕНИЯ:
- Теплый, гостеприимный, "итальяно-калабрийский" колорит.
- Краткие, но информативные ответы.
- Используйте эмодзи (🌊, 🍕, ☀️, 🇮🇹), чтобы создать настроение.
- Отвечайте на том языке, на котором спрашивает гость.
`;
